export type ProductLang = "en" | "hy";

const careFeaturesEn = [
  "AI-assisted OPG analysis",
  "Possible findings with clinician review",
  "Smart patient profile and OPG history",
  "Tooth-level follow-up planning",
  "Automated clinic WhatsApp outreach",
  "Patient response and appointment workflow",
  "Follow-up dashboard and treatment history",
  "Patient-return tracking"
];

const careFeaturesHy = [
  "AI-ով աջակցվող OPG վերլուծություն",
  "Հնարավոր արդյունքներ՝ բժշկի վերանայմամբ",
  "Խելացի պացիենտի քարտ և OPG պատմություն",
  "Ատամի մակարդակով follow-up պլանավորում",
  "Կլինիկայի WhatsApp outreach",
  "Պացիենտի պատասխանների և այցերի workflow",
  "Follow-up վահանակ և բուժման պատմություն",
  "Պացիենտի վերադարձի վերահսկում"
];

export const PRODUCT_COPY = {
  en: {
    nav: { product: "Product", how: "How it works", pricing: "Pricing", safety: "Clinical & Safety", about: "About / Contact", login: "Sign in", access: "Request access" },
    hero: { eyebrow: "AI-powered OPG intelligence + patient follow-up", title: "Turn Every OPG Into Actionable Patient Follow-up.", lead: "Teta2 Care helps dental clinics review possible OPG findings, organize patient records, coordinate follow-up and bring patients back into care.", primary: "Open clinic workspace", secondary: "See how it works", proof: ["AI-assisted possible findings", "Dentist review stays in control", "Care closes the follow-up loop"] },
    problem: { kicker: "From image to action", title: "An OPG should not end as a forgotten image.", body: "Teta2 Care turns the panoramic X-ray into a structured clinical workflow: possible findings, a smart patient file and organized follow-up that helps the clinic act before the patient disappears.", cards: [["Understand faster", "Organize possible findings by tooth or region where the model supports it."], ["Keep the record", "Store OPGs, analyses and clinician review inside the patient’s smart dental file."], ["Follow through", "Turn clinician-approved findings into follow-up actions, WhatsApp outreach and patient-return tracking."]] },
    workflow: { kicker: "Core workflow", title: "OPG → Understand → Record → Follow → Return", steps: [["01", "Create patient", "Start a smart patient profile with essential contact and clinical context."], ["02", "Upload OPG", "Upload the patient’s panoramic X-ray into protected clinical storage."], ["03", "AI-assisted analysis", "Teta2 Care produces possible findings for dentist examination."], ["04", "Clinician review", "Review findings visually and confirm or reject them."], ["05", "Smart patient file", "Keep OPG, analysis and review history together."], ["06", "Care follow-up", "Create tooth-based follow-up timing from approved clinical context."], ["07", "Patient message", "Send clinic WhatsApp outreach and handle the staged response workflow."], ["08", "Patient return", "Coordinate appointment confirmation and track the return to clinic."]] },
    plans: { kicker: "One complete plan", title: "Everything the clinic needs in Teta2 Care.", scan: { name: "Teta2 Care", tagline: "Clinical intelligence connected to patient follow-up.", outcome: "OPG → Record → Follow → Return", features: careFeaturesEn }, care: { name: "Teta2 Care", tagline: "Never lose a patient who needs follow-up.", outcome: "OPG → Understand → Record → Follow → Return", features: careFeaturesEn } },
    safety: { kicker: "Clinical safety by design", title: "AI supports the dentist. It does not replace clinical judgment.", body: "Teta2 Care presents AI-assisted possible findings for professional examination. The clinician remains responsible for review, diagnosis and care decisions.", items: [["Human in the loop", "Every possible finding stays reviewable by the dentist."], ["Protected clinical data", "Access control, encrypted storage and audit logging are part of the platform architecture."], ["Responsible claims", "Teta2 does not present model output as a definitive diagnosis or claim unvalidated diagnostic accuracy."]] },
    pricing: { title: "One Teta2 Care subscription.", lead: "One complete clinic product with a fixed 30-day paid access period. Renewal extends access without resetting existing clinic data.", monthly: "30 days", annual: "Each verified renewal adds another 30 days of access.", market: "Plan", unlimited: "Complete Teta2 Care access", choose: "Request access" },
    about: { title: "Teta2 is built around one clinical loop.", lead: "We build focused dental AI for OPG intelligence and patient follow-up, not a generic clinic CRM. Commercial access is provided through the Teta2 Care onboarding workflow.", principle: "Simple beats comprehensive. OPG stays at the center. Every AI finding should lead to a useful clinical workflow.", roadmap: ["OPG core: reliable upload, analysis, findings and patient record", "Care workflow: follow-up, messaging, response tracking and patient return", "Clinical intelligence: stronger tooth mapping and longitudinal comparison after validation", "Operational intelligence only where it supports the core clinic workflow"] },
    access: { title: "Request Teta2 Care access", lead: "Submit your clinic details for review. Approved requests receive payment instructions by email and are activated for exactly 30 days after payment verification.", note: "Teta2 Care is the only paid clinic plan. Credentials are issued only after payment is verified and the clinic workspace is activated.", login: "Already activated? Sign in" },
    clinic: { dashboard: "Dashboard", patients: "Patients", opg: "OPG Analysis", followups: "Follow-ups", messages: "Messages", settings: "Settings", dashboardTitle: "Clinical action dashboard", dashboardLead: "The OPG-to-follow-up loop, using live clinic data.", newPatient: "New patient", selectPatient: "Select patient", upload: "Upload OPG", analyze: "Run AI-assisted analysis", possibleFinding: "possible finding", requiresExam: "Requires dentist examination", noPatient: "Select a patient to open the smart patient file.", noFollowups: "No follow-ups are currently visible for your scope.", messagesLead: "Patient follow-up messaging for the selected patient, using the clinic’s connected WhatsApp sender.", careRecord: "Smart Patient File", overview: "Overview", opgHistory: "OPG History", findings: "Possible Findings", timeline: "Follow-up", messageHistory: "Messages" }
  },
  hy: {
    nav: { product: "Արտադրանք", how: "Ինչպես է աշխատում", pricing: "Գներ", safety: "Կլինիկական անվտանգություն", about: "Մեր մասին / Կապ", login: "Մուտք", access: "Մուտքի հարցում" },
    hero: { eyebrow: "AI-ով OPG վերլուծություն + պացիենտի հետագա վերահսկում", title: "Յուրաքանչյուր OPG-ն վերածեք գործնական հետագա վերահսկման։", lead: "Teta2 Care-ը օգնում է կլինիկաներին վերանայել OPG-ի հնարավոր արդյունքները, կազմակերպել պացիենտի տվյալները և կառավարել հետագա կապը։", primary: "Բացել կլինիկայի workspace-ը", secondary: "Ինչպես է աշխատում", proof: ["AI-ով աջակցվող հնարավոր արդյունքներ", "Բժիշկը մնում է վերահսկման կենտրոնում", "Care-ը փակում է follow-up շղթան"] },
    problem: { kicker: "Պատկերից դեպի գործողություն", title: "OPG-ն չպետք է ավարտվի որպես մոռացված պատկեր։", body: "Teta2 Care-ը պանորամիկ ռենտգենը վերածում է կառուցվածքային կլինիկական workflow-ի՝ հնարավոր արդյունքներ, պացիենտի խելացի քարտ և կազմակերպված follow-up։", cards: [["Ավելի արագ հասկանալ", "Հնարավոր արդյունքները կազմակերպվում են ըստ ատամի կամ շրջանի, որտեղ մոդելը դա աջակցում է։"], ["Պահպանել պատմությունը", "OPG-ները, վերլուծությունները և բժշկի վերանայումը պահվում են պացիենտի խելացի քարտում։"], ["Շարունակել վերահսկումը", "Բժշկի հաստատած արդյունքները վերածվում են follow-up գործողությունների, WhatsApp outreach-ի և վերադարձի վերահսկման։"]] },
    workflow: { kicker: "Հիմնական ընթացք", title: "OPG → Հասկանալ → Պահպանել → Հետևել → Վերադարձ", steps: [["01", "Ստեղծել պացիենտ", "Ստեղծեք պացիենտի քարտ՝ հիմնական կոնտակտային և կլինիկական տվյալներով։"], ["02", "Վերբեռնել OPG", "Վերբեռնեք պացիենտի պանորամիկ ռենտգենը պաշտպանված կլինիկական պահոց։"], ["03", "AI վերլուծություն", "Teta2 Care-ը ներկայացնում է հնարավոր արդյունքներ բժշկի զննման համար։"], ["04", "Բժշկի վերանայում", "Վերանայեք արդյունքները և հաստատեք կամ մերժեք դրանք։"], ["05", "Խելացի պացիենտի քարտ", "OPG-ն, վերլուծությունը և վերանայման պատմությունը պահեք միասին։"], ["06", "Care follow-up", "Ստեղծեք ատամի մակարդակով follow-up ժամանակացույց։"], ["07", "Պացիենտի հաղորդագրություն", "Ուղարկեք WhatsApp outreach և կառավարեք փուլային պատասխանները։"], ["08", "Պացիենտի վերադարձ", "Համակարգեք այցի հաստատումը և վերահսկեք վերադարձը կլինիկա։"]] },
    plans: { kicker: "Մեկ ամբողջական պլան", title: "Կլինիկայի ամբողջ workflow-ը Teta2 Care-ում։", scan: { name: "Teta2 Care", tagline: "Կլինիկական ինտելեկտ՝ կապված պացիենտի follow-up-ի հետ։", outcome: "OPG → Քարտ → Follow-up → Վերադարձ", features: careFeaturesHy }, care: { name: "Teta2 Care", tagline: "Մի կորցրեք follow-up-ի կարիք ունեցող պացիենտին։", outcome: "OPG → Հասկանալ → Պահպանել → Հետևել → Վերադարձ", features: careFeaturesHy } },
    safety: { kicker: "Կլինիկական անվտանգություն ըստ դիզայնի", title: "AI-ն աջակցում է բժշկին և չի փոխարինում կլինիկական դատողությանը։", body: "Teta2 Care-ը ներկայացնում է AI-ով աջակցվող հնարավոր արդյունքներ մասնագիտական զննման համար։ Վերջնական վերանայումը, ախտորոշումը և բուժման որոշումը մնում են բժշկին։", items: [["Մարդը վերահսկման շղթայում", "Յուրաքանչյուր հնարավոր արդյունք հասանելի է բժշկի վերանայման համար։"], ["Պաշտպանված կլինիկական տվյալներ", "Մուտքի կառավարումը, գաղտնագրված պահոցը և աուդիտի գրանցումը հարթակի ճարտարապետության մաս են։"], ["Պատասխանատու ձևակերպումներ", "Teta2-ը AI արդյունքը չի ներկայացնում որպես վերջնական ախտորոշում։"]] },
    pricing: { title: "Մեկ Teta2 Care բաժանորդագրություն։", lead: "Մեկ ամբողջական կլինիկական արտադրանք՝ ֆիքսված 30-օրյա վճարովի մուտքով։ Թարմացումը երկարացնում է մուտքը՝ առանց տվյալների վերակայման։", monthly: "30 օր", annual: "Յուրաքանչյուր հաստատված թարմացում ավելացնում է ևս 30 օր։", market: "Պլան", unlimited: "Teta2 Care-ի ամբողջական հասանելիություն", choose: "Մուտքի հարցում" },
    about: { title: "Teta2-ը կառուցված է մեկ կլինիկական շղթայի շուրջ։", lead: "Մենք կառուցում ենք կենտրոնացված dental AI՝ OPG ինտելեկտի և պացիենտի follow-up-ի համար, ոչ թե ընդհանուր CRM։ Առևտրային մուտքը կատարվում է Teta2 Care onboarding workflow-ով։", principle: "Պարզը գերադասելի է համապարփակից։ OPG-ն մնում է կենտրոնում։ Յուրաքանչյուր AI արդյունք պետք է բերի օգտակար կլինիկական workflow-ի։", roadmap: ["OPG հիմք՝ հուսալի վերբեռնում, վերլուծություն և պացիենտի քարտ", "Care workflow՝ follow-up, հաղորդագրություններ և վերադարձ", "Կլինիկական ինտելեկտ՝ ավելի ուժեղ ատամային mapping և longitudinal comparison", "Օպերացիոն ինտելեկտ միայն այնտեղ, որտեղ աջակցում է հիմնական կլինիկական workflow-ին"] },
    access: { title: "Հարցում Teta2 Care մուտքի համար", lead: "Ուղարկեք կլինիկայի տվյալները վերանայման համար։ Հաստատվելու դեպքում վճարման տվյալները կուղարկվեն էլ. փոստով, իսկ վճարման ստուգումից հետո մուտքը կակտիվացվի ուղիղ 30 օրով։", note: "Teta2 Care-ը միակ վճարովի կլինիկական պլանն է։ Մուտքի տվյալները տրամադրվում են միայն վճարման հաստատումից և workspace-ի ակտիվացումից հետո։", login: "Արդեն ակտիվացվա՞ծ է։ Մուտք" },
    clinic: { dashboard: "Վահանակ", patients: "Պացիենտներ", opg: "OPG վերլուծություն", followups: "Follow-up", messages: "Հաղորդագրություններ", settings: "Կարգավորումներ", dashboardTitle: "Կլինիկական գործողությունների վահանակ", dashboardLead: "OPG-ից follow-up ամբողջ շղթան՝ իրական կլինիկական տվյալներով։", newPatient: "Նոր պացիենտ", selectPatient: "Ընտրել պացիենտ", upload: "Վերբեռնել OPG", analyze: "Գործարկել AI վերլուծություն", possibleFinding: "հնարավոր արդյունք", requiresExam: "Պահանջում է բժշկի զննում", noPatient: "Ընտրեք պացիենտ՝ խելացի քարտը բացելու համար։", noFollowups: "Ձեր հասանելիության շրջանակում follow-up չկա։", messagesLead: "Պացիենտի follow-up հաղորդագրությունները՝ կլինիկայի միացված WhatsApp համարից։", careRecord: "Խելացի պացիենտի քարտ", overview: "Ընդհանուր", opgHistory: "OPG պատմություն", findings: "Հնարավոր արդյունքներ", timeline: "Follow-up", messageHistory: "Հաղորդագրություններ" }
  }
} as const;

export function productCopy(lang: ProductLang) {
  return PRODUCT_COPY[lang];
}
