import { useEffect } from "react";

type Lang = "hy" | "ru";
type Pair = { en: string; hy: string; ru: string };

const COPY: Pair[] = [
  {
    en: "This policy applies to teta2.com, the clinic dashboard and the Teta2 access-request process. For clinic patient data, the clinic determines why the data is used and is normally the data controller; Teta2 processes that data to provide the contracted platform. For access requests, account administration, security and support, Teta2 determines the relevant processing purposes.",
    hy: "Այս քաղաքականությունը կիրառվում է teta2.com կայքի, կլինիկայի վահանակի և Teta2 մուտքի հայտերի գործընթացի նկատմամբ։ Կլինիկայի պացիենտների տվյալների դեպքում կլինիկան որոշում է դրանց օգտագործման նպատակը և սովորաբար հանդիսանում է տվյալների պատասխանատու, իսկ Teta2-ը մշակում է տվյալները՝ պայմանագրային հարթակը տրամադրելու համար։ Մուտքի հայտերի, հաշիվների կառավարման, անվտանգության և աջակցության դեպքում մշակման համապատասխան նպատակները որոշում է Teta2-ը։",
    ru: "Настоящая политика применяется к teta2.com, панели клиники и процессу подачи заявки на доступ к Teta2. В отношении данных пациентов клиника определяет цели их использования и, как правило, является оператором данных; Teta2 обрабатывает эти данные для предоставления согласованной платформы. Для заявок на доступ, администрирования учетных записей, безопасности и поддержки соответствующие цели обработки определяет Teta2."
  },
  {
    en: "Teta2 processes only information provided through the service or generated by its operation.",
    hy: "Teta2-ը մշակում է միայն ծառայության միջոցով տրամադրված կամ դրա աշխատանքի ընթացքում ստեղծված տեղեկությունները։",
    ru: "Teta2 обрабатывает только информацию, предоставленную через сервис или созданную в ходе его работы."
  },
  {
    en: "Clinic application details: clinic name, country, city, address if supplied, website, contact person, role, email, phone, number of dentists and branches, and notes.",
    hy: "Կլինիկայի հայտի տվյալներ՝ կլինիկայի անվանում, երկիր, քաղաք, տրամադրման դեպքում՝ հասցե և կայք, կոնտակտային անձ, դեր, էլ․ փոստ, հեռախոս, ատամնաբույժների ու մասնաճյուղերի քանակ և նշումներ։",
    ru: "Данные заявки клиники: название клиники, страна, город, при наличии — адрес и сайт, контактное лицо, должность, email, телефон, количество стоматологов и филиалов, а также примечания."
  },
  {
    en: "Account and access data: username, email, role, clinic and branch permissions, authentication tokens and security events.",
    hy: "Հաշվի և մուտքի տվյալներ՝ օգտանուն, էլ․ փոստ, դեր, կլինիկայի և մասնաճյուղերի թույլտվություններ, նույնականացման նշաններ և անվտանգության իրադարձություններ։",
    ru: "Данные учетной записи и доступа: имя пользователя, email, роль, права клиники и филиалов, токены аутентификации и события безопасности."
  },
  {
    en: "Patient and clinical data entered by an authorized clinic: identifiers, contact details, date of birth, sex, clinical records, OPG images, AI-assisted possible findings, clinician reviews, follow-up plans, messages and appointments.",
    hy: "Լիազորված կլինիկայի մուտքագրած պացիենտի և կլինիկական տվյալներ՝ նույնականացուցիչներ, կոնտակտային տվյալներ, ծննդյան ամսաթիվ, սեռ, կլինիկական գրառումներ, OPG պատկերներ, AI-աջակցվող հնարավոր փոփոխություններ, բժշկի վերանայումներ, հետագա վերահսկման պլաններ, հաղորդագրություններ և այցեր։",
    ru: "Данные пациентов и клинические данные, введенные уполномоченной клиникой: идентификаторы, контактные данные, дата рождения, пол, клинические записи, изображения OPG, возможные изменения, выявленные с поддержкой ИИ, результаты проверки врачом, планы последующего наблюдения, сообщения и приемы."
  },
  {
    en: "Operational data: request identifiers, timestamps, delivery states, audit records and limited network/security metadata.",
    hy: "Գործառնական տվյալներ՝ հարցումների նույնականացուցիչներ, ժամանակային նշումներ, առաքման կարգավիճակներ, աուդիտի գրառումներ և սահմանափակ ցանցային ու անվտանգության մետատվյալներ։",
    ru: "Операционные данные: идентификаторы запросов, временные метки, статусы доставки, журналы аудита и ограниченные сетевые метаданные и метаданные безопасности."
  },
  {
    en: "Payment administration data: payment reference, receipt notes, verification status and related correspondence. Teta2 does not currently collect payment-card data through an online checkout.",
    hy: "Վճարումների կառավարման տվյալներ՝ վճարման նույնականացուցիչ, անդորրագրի նշումներ, ստուգման կարգավիճակ և համապատասխան հաղորդակցություն։ Teta2-ը ներկայում առցանց վճարման ձևով չի հավաքում վճարային քարտերի տվյալներ։",
    ru: "Данные для администрирования платежей: идентификатор платежа, сведения о квитанции, статус проверки и связанная переписка. В настоящее время Teta2 не собирает данные платежных карт через онлайн-форму оплаты."
  },
  {
    en: "Information is used to review access requests, create and secure clinic workspaces, provide OPG and follow-up functions, deliver support, administer subscriptions and payments, prevent misuse, maintain auditability and comply with applicable law. Processing is based, as applicable, on performance of the service agreement, steps requested before entering that agreement, legitimate security and operational interests, legal obligations, and the clinic's lawful authority to process patient information.",
    hy: "Տեղեկություններն օգտագործվում են մուտքի հայտերը ստուգելու, կլինիկայի աշխատանքային միջավայրը ստեղծելու և պաշտպանելու, OPG ու հետագա վերահսկման գործառույթները տրամադրելու, աջակցություն մատուցելու, բաժանորդագրություններն ու վճարումները կառավարելու, չարաշահումները կանխելու, աուդիտային հետագծելիությունն ապահովելու և կիրառելի օրենսդրությանը համապատասխանելու համար։ Մշակման հիմքերը, ըստ կիրառելիության, ներառում են ծառայության պայմանագրի կատարումը, պայմանագրի կնքումից առաջ պահանջված քայլերը, անվտանգության ու գործառնական օրինական շահերը, իրավական պարտավորությունները և պացիենտների տվյալները մշակելու կլինիկայի օրինական իրավասությունը։",
    ru: "Информация используется для проверки заявок на доступ, создания и защиты рабочих пространств клиник, предоставления функций OPG и последующего наблюдения, поддержки, администрирования подписок и платежей, предотвращения злоупотреблений, обеспечения аудируемости и соблюдения применимого законодательства. В зависимости от ситуации обработка основывается на исполнении договора на оказание услуг, действиях, запрошенных до заключения договора, законных интересах в области безопасности и эксплуатации, юридических обязанностях и законных полномочиях клиники на обработку данных пациентов."
  },
  {
    en: "The production service uses infrastructure providers to host the frontend, application services and databases. The PostgreSQL database is hosted on AWS infrastructure. Authorized service providers receive only the information needed for hosting, email delivery, secure file storage or clinic-enabled messaging. When a clinic connects or uses WhatsApp, message and recipient information is also handled under the applicable WhatsApp/Meta terms. Teta2 does not sell patient or clinic personal data.",
    hy: "Արտադրական ծառայությունն օգտագործում է ենթակառուցվածքային մատակարարներ՝ ֆրոնտենդը, հավելվածի ծառայությունները և տվյալների բազաները տեղակայելու համար։ PostgreSQL տվյալների բազան տեղակայված է AWS ենթակառուցվածքում։ Լիազորված ծառայությունների մատակարարները ստանում են միայն հոսթինգի, էլ․ փոստի առաքման, անվտանգ ֆայլային պահոցի կամ կլինիկայի միացրած հաղորդագրությունների համար անհրաժեշտ տեղեկությունները։ Երբ կլինիկան միացնում կամ օգտագործում է WhatsApp-ը, հաղորդագրությունների և ստացողների տվյալները նույնպես մշակվում են WhatsApp/Meta-ի կիրառելի պայմանների համաձայն։ Teta2-ը չի վաճառում պացիենտների կամ կլինիկաների անձնական տվյալները։",
    ru: "Рабочая версия сервиса использует инфраструктурных поставщиков для размещения фронтенда, прикладных сервисов и баз данных. База данных PostgreSQL размещена в инфраструктуре AWS. Уполномоченные поставщики услуг получают только информацию, необходимую для хостинга, доставки электронной почты, защищенного хранения файлов или обмена сообщениями, подключенного клиникой. При подключении или использовании WhatsApp данные сообщений и получателей также обрабатываются в соответствии с применимыми условиями WhatsApp/Meta. Teta2 не продает персональные данные пациентов или клиник."
  },
  {
    en: "Data is retained while the clinic workspace is active and afterward where needed to preserve the clinic record, meet legal or security obligations, resolve disputes or support renewal. Subscription expiry locks access; it does not automatically delete clinic data. A clinic may request closure or deletion at the contact address below. Requests are assessed against the clinic's instructions, patient-safety needs and mandatory retention duties. Browser session tokens are removed when the browser session ends or the user signs out.",
    hy: "Տվյալները պահպանվում են կլինիկայի աշխատանքային միջավայրի ակտիվ լինելու ընթացքում և դրանից հետո՝ այնքանով, որքանով անհրաժեշտ է կլինիկայի գրառումները պահպանելու, իրավական կամ անվտանգության պարտավորությունները կատարելու, վեճերը լուծելու կամ երկարաձգումն ապահովելու համար։ Բաժանորդագրության ավարտը կողպում է մուտքը, բայց ինքնաբերաբար չի ջնջում կլինիկայի տվյալները։ Կլինիկան կարող է ստորև նշված հասցեով պահանջել աշխատանքային միջավայրի փակում կամ տվյալների ջնջում։ Հարցումները գնահատվում են կլինիկայի ցուցումների, պացիենտի անվտանգության կարիքների և պարտադիր պահպանման պահանջների համատեքստում։ Դիտարկչի աշխատաշրջանի նշանները հեռացվում են աշխատաշրջանի ավարտից կամ օգտատիրոջ դուրս գալուց հետո։",
    ru: "Данные хранятся, пока рабочее пространство клиники активно, а затем — в той мере, в которой это необходимо для сохранения записей клиники, выполнения юридических или защитных обязательств, разрешения споров или продления доступа. Окончание подписки блокирует доступ, но не удаляет данные клиники автоматически. Клиника может запросить закрытие рабочего пространства или удаление данных по указанному ниже адресу. Запросы оцениваются с учетом указаний клиники, требований безопасности пациентов и обязательных сроков хранения. Токены браузерной сессии удаляются по завершении сессии или при выходе пользователя."
  },
  {
    en: "Teta2 uses access controls, tenant separation, protected transport, encrypted credential handling, audit records and restricted administrative access. No online service can promise absolute security. Clinics must keep credentials confidential, use authorized devices and report suspected access promptly.",
    hy: "Teta2-ը կիրառում է մուտքի վերահսկում, կլինիկաների տվյալների տարանջատում, պաշտպանված փոխանցում, նույնականացման տվյալների կոդավորված մշակում, աուդիտի գրառումներ և սահմանափակ վարչական մուտք։ Ոչ մի առցանց ծառայություն չի կարող երաշխավորել բացարձակ անվտանգություն։ Կլինիկաները պարտավոր են մուտքի տվյալները գաղտնի պահել, օգտագործել լիազորված սարքեր և անհապաղ հայտնել կասկածելի մուտքի մասին։",
    ru: "Teta2 использует контроль доступа, разделение данных клиник, защищенную передачу данных, шифрованную обработку учетных данных, журналы аудита и ограниченный административный доступ. Ни один онлайн-сервис не может гарантировать абсолютную безопасность. Клиники обязаны хранить учетные данные в тайне, использовать только авторизованные устройства и незамедлительно сообщать о подозрительном доступе."
  },
  {
    en: "Under applicable Armenian data-protection law, individuals may request information about processing and, where applicable, access, correction, blocking or deletion. Patient requests should normally be directed to the treating clinic because the clinic controls the patient record. Teta2 will assist the clinic where required. Clinics must have a lawful basis and provide any required patient notice before uploading personal or clinical data.",
    hy: "Հայաստանի տվյալների պաշտպանության կիրառելի օրենսդրության համաձայն՝ անձինք կարող են պահանջել տեղեկություն մշակման մասին և, կիրառելի դեպքերում, մուտք, ուղղում, արգելափակում կամ ջնջում։ Պացիենտների հարցումները սովորաբար պետք է ուղղվեն բուժող կլինիկային, քանի որ պացիենտի քարտը վերահսկում է կլինիկան։ Անհրաժեշտության դեպքում Teta2-ը կաջակցի կլինիկային։ Անձնական կամ կլինիկական տվյալներ վերբեռնելուց առաջ կլինիկան պետք է ունենա օրինական հիմք և պացիենտին տրամադրի պահանջվող ծանուցումները։",
    ru: "В соответствии с применимым законодательством Армении о защите данных физические лица могут запрашивать информацию об обработке и, где это применимо, доступ, исправление, блокировку или удаление. Запросы пациентов обычно следует направлять лечащей клинике, поскольку именно клиника контролирует карту пациента. При необходимости Teta2 окажет клинике содействие. До загрузки персональных или клинических данных клиника должна иметь законное основание и предоставить пациенту все требуемые уведомления."
  },
  {
    en: "Service providers may process data outside the individual's country. Teta2 uses contractual and technical safeguards appropriate to the service and applicable law. Material policy changes will be posted on this page with a revised date.",
    hy: "Ծառայությունների մատակարարները կարող են տվյալներ մշակել անձի երկրից դուրս։ Teta2-ը կիրառում է ծառայությանը և կիրառելի օրենսդրությանը համապատասխան պայմանագրային ու տեխնիկական պաշտպանական միջոցներ։ Քաղաքականության էական փոփոխությունները կհրապարակվեն այս էջում՝ թարմացված ամսաթվով։",
    ru: "Поставщики услуг могут обрабатывать данные за пределами страны физического лица. Teta2 использует договорные и технические меры защиты, соответствующие сервису и применимому законодательству. Существенные изменения политики будут опубликованы на этой странице с обновленной датой."
  },
  {
    en: "By requesting access, paying for a subscription or using a clinic workspace, the clinic and its authorized users agree to these Terms. The person accepting must be legally able to act for the clinic. Teta2 is intended for professional dental-clinic use, not direct patient self-diagnosis or emergency care.",
    hy: "Մուտք խնդրելով, բաժանորդագրության համար վճարելով կամ կլինիկայի աշխատանքային միջավայրն օգտագործելով՝ կլինիկան և նրա լիազորված օգտատերերը համաձայնում են այս պայմաններին։ Համաձայնություն տվող անձը պետք է իրավասու լինի գործել կլինիկայի անունից։ Teta2-ը նախատեսված է ատամնաբուժական կլինիկաների մասնագիտական օգտագործման համար և նախատեսված չէ պացիենտների ինքնուրույն ախտորոշման կամ շտապ բուժօգնության համար։",
    ru: "Запрашивая доступ, оплачивая подписку или используя рабочее пространство клиники, клиника и ее уполномоченные пользователи соглашаются с настоящими Условиями. Лицо, принимающее их, должно иметь законное право действовать от имени клиники. Teta2 предназначен для профессионального использования стоматологическими клиниками, а не для самостоятельной диагностики пациентами или экстренной помощи."
  },
  {
    en: "Public self-service activation is not currently available. Teta2 reviews each application, sends payment instructions when approved, verifies payment manually and then issues clinic credentials. The subscription period and price are those shown in the approved offer or payment instructions. The current standard activation flow provisions a fixed 30-day period. Renewal restores access to the same workspace unless otherwise agreed.",
    hy: "Հանրային ինքնուրույն ակտիվացումը ներկայում հասանելի չէ։ Teta2-ը ստուգում է յուրաքանչյուր հայտ, հաստատումից հետո ուղարկում վճարման հրահանգները, ձեռքով ստուգում վճարումը և ապա տրամադրում կլինիկայի մուտքի տվյալները։ Բաժանորդագրության ժամկետն ու գինը նշված են հաստատված առաջարկում կամ վճարման հրահանգներում։ Ներկայիս ստանդարտ ակտիվացումը նախատեսում է ֆիքսված 30-օրյա ժամկետ։ Երկարաձգումը վերականգնում է նույն աշխատանքային միջավայրի մուտքը, եթե այլ բան համաձայնեցված չէ։",
    ru: "Публичная самостоятельная активация в настоящее время недоступна. Teta2 проверяет каждую заявку, после одобрения отправляет инструкции по оплате, вручную подтверждает платеж и затем выдает клинике учетные данные. Срок и стоимость подписки указаны в одобренном предложении или инструкциях по оплате. Текущий стандартный процесс активации предусматривает фиксированный срок 30 дней. Продление восстанавливает доступ к тому же рабочему пространству, если стороны не договорились иначе."
  },
  {
    en: "Teta2 provides workflow software and AI-assisted possible findings. It does not provide a final diagnosis, treatment decision or substitute for examination by a qualified dentist. The clinic remains responsible for clinical review, patient consent, diagnosis, treatment, communications and compliance with professional rules.",
    hy: "Teta2-ը տրամադրում է կլինիկական գործընթացի ծրագրային գործիքներ և AI-աջակցվող հնարավոր փոփոխություններ։ Այն չի տալիս վերջնական ախտորոշում կամ բուժման որոշում և չի փոխարինում որակավորված ատամնաբույժի զննմանը։ Կլինիկան շարունակում է պատասխանատու լինել կլինիկական վերանայման, պացիենտի համաձայնության, ախտորոշման, բուժման, հաղորդակցության և մասնագիտական կանոնների պահպանման համար։",
    ru: "Teta2 предоставляет программные инструменты для клинического процесса и возможные изменения, выявленные с поддержкой ИИ. Сервис не устанавливает окончательный диагноз, не принимает решение о лечении и не заменяет осмотр квалифицированным стоматологом. Клиника остается ответственной за клиническую проверку, согласие пациента, диагноз, лечение, коммуникации и соблюдение профессиональных правил."
  },
  {
    en: "The clinic must provide accurate information, use patient data lawfully, limit access to authorized staff, protect credentials, review AI output before relying on it and keep its own legally required clinical records. The clinic must not upload data it is not authorized to process.",
    hy: "Կլինիկան պարտավոր է տրամադրել ճշգրիտ տեղեկություններ, պացիենտների տվյալներն օգտագործել օրինականորեն, մուտքը սահմանափակել լիազորված աշխատակիցներով, պաշտպանել մուտքի տվյալները, AI արդյունքը վերանայել մինչև դրա վրա հիմնվելը և վարել օրենքով պահանջվող իր կլինիկական գրառումները։ Կլինիկան չպետք է վերբեռնի տվյալներ, որոնք մշակելու իրավասություն չունի։",
    ru: "Клиника обязана предоставлять точную информацию, законно использовать данные пациентов, ограничивать доступ уполномоченными сотрудниками, защищать учетные данные, проверять результат ИИ до того, как на него полагаться, и вести собственные клинические записи, требуемые законом. Клиника не должна загружать данные, которые она не уполномочена обрабатывать."
  },
  {
    en: "Users may not attempt unauthorized access, bypass tenant controls, probe or overload the service, reverse engineer protected components, upload malicious or unlawful content, use the system to make unsupervised clinical decisions, or use ordinary clinic access for automated bulk processing or resale. Fair-use limits may be applied to abnormal automation or API abuse.",
    hy: "Օգտատերերը չեն կարող փորձել չարտոնված մուտք ստանալ, շրջանցել կլինիկաների տարանջատման վերահսկումները, փորձարկել կամ գերբեռնել ծառայությունը, հետադարձ ինժեներիայով ուսումնասիրել պաշտպանված բաղադրիչները, վերբեռնել վնասակար կամ անօրինական բովանդակություն, համակարգն օգտագործել առանց բժշկի վերահսկման կլինիկական որոշումների համար կամ սովորական կլինիկայի մուտքն օգտագործել ավտոմատ զանգվածային մշակման կամ վերավաճառքի նպատակով։ Աննորմալ ավտոմատացման կամ API չարաշահման դեպքում կարող են կիրառվել արդար օգտագործման սահմանափակումներ։",
    ru: "Пользователям запрещается пытаться получить несанкционированный доступ, обходить механизмы разделения данных клиник, тестировать на уязвимости или перегружать сервис, выполнять обратную разработку защищенных компонентов, загружать вредоносный или незаконный контент, использовать систему для клинических решений без контроля врача либо применять обычный доступ клиники для автоматизированной массовой обработки или перепродажи. При аномальной автоматизации или злоупотреблении API могут применяться ограничения добросовестного использования."
  },
  {
    en: "Clinic-enabled WhatsApp messaging depends on the clinic's connected account and third-party availability. The clinic is responsible for lawful recipient consent, message content and communication timing. Third-party services remain subject to their own terms and may change independently of Teta2.",
    hy: "Կլինիկայի միացրած WhatsApp հաղորդագրությունները կախված են կլինիկայի կապակցված հաշվից և երրորդ կողմի ծառայության հասանելիությունից։ Կլինիկան պատասխանատու է ստացողի օրինական համաձայնության, հաղորդագրության բովանդակության և հաղորդակցության ժամանակի համար։ Երրորդ կողմի ծառայությունները գործում են իրենց պայմաններով և կարող են փոխվել Teta2-ից անկախ։",
    ru: "Обмен сообщениями WhatsApp, подключенный клиникой, зависит от связанной учетной записи клиники и доступности стороннего сервиса. Клиника отвечает за законность согласия получателя, содержание сообщений и время коммуникации. Сторонние сервисы действуют на собственных условиях и могут изменяться независимо от Teta2."
  },
  {
    en: "Teta2 may perform maintenance and cannot guarantee uninterrupted availability. Access may be suspended for non-payment, expired subscription, security risk, unlawful use or material breach. The clinic may stop using the service and request workspace closure by email. Data handling after expiry or closure follows the Privacy Policy and applicable law.",
    hy: "Teta2-ը կարող է կատարել տեխնիկական սպասարկում և չի կարող երաշխավորել անընդհատ հասանելիություն։ Մուտքը կարող է կասեցվել չվճարման, բաժանորդագրության ավարտի, անվտանգության ռիսկի, անօրինական օգտագործման կամ էական խախտման դեպքում։ Կլինիկան կարող է դադարեցնել ծառայության օգտագործումը և էլ․ փոստով խնդրել փակել աշխատանքային միջավայրը։ Ժամկետի ավարտից կամ փակումից հետո տվյալների մշակումը կատարվում է Գաղտնիության քաղաքականության և կիրառելի օրենսդրության համաձայն։",
    ru: "Teta2 может проводить техническое обслуживание и не гарантирует непрерывную доступность. Доступ может быть приостановлен из-за неоплаты, окончания подписки, риска безопасности, незаконного использования или существенного нарушения. Клиника может прекратить использование сервиса и запросить закрытие рабочего пространства по электронной почте. Обработка данных после истечения срока или закрытия осуществляется в соответствии с Политикой конфиденциальности и применимым законодательством."
  },
  {
    en: "Teta2 and its software, interface and platform materials remain protected by applicable intellectual-property law. Clinics retain their rights in clinic and patient data. A subscription grants a limited, non-exclusive, non-transferable right to use the service during the active period. Feedback may be used to improve the platform without identifying patients or disclosing clinic-confidential information.",
    hy: "Teta2-ը, դրա ծրագրային ապահովումը, միջերեսը և հարթակի նյութերը պաշտպանվում են կիրառելի մտավոր սեփականության օրենսդրությամբ։ Կլինիկաները պահպանում են իրենց իրավունքները կլինիկայի և պացիենտների տվյալների նկատմամբ։ Բաժանորդագրությունը տալիս է ծառայությունն ակտիվ ժամանակահատվածում օգտագործելու սահմանափակ, ոչ բացառիկ և չփոխանցվող իրավունք։ Արձագանքը կարող է օգտագործվել հարթակը բարելավելու համար՝ առանց պացիենտներին նույնականացնելու կամ կլինիկայի գաղտնի տեղեկությունները բացահայտելու։",
    ru: "Teta2, его программное обеспечение, интерфейс и материалы платформы защищаются применимым законодательством об интеллектуальной собственности. Клиники сохраняют права на данные клиники и пациентов. Подписка предоставляет ограниченное, неисключительное и непередаваемое право использовать сервис в течение активного периода. Обратная связь может использоваться для улучшения платформы без идентификации пациентов и раскрытия конфиденциальной информации клиники."
  },
  {
    en: "To the extent permitted by law, Teta2 is not liable for clinical decisions, missed diagnoses, treatment outcomes, third-party messaging failures or losses caused by unauthorized clinic use. Nothing in these Terms excludes liability that cannot lawfully be excluded. Disputes should first be raised at the support email for good-faith resolution.",
    hy: "Օրենքով թույլատրելի սահմաններում Teta2-ը պատասխանատվություն չի կրում կլինիկական որոշումների, բաց թողնված ախտորոշումների, բուժման արդյունքների, երրորդ կողմի հաղորդագրությունների ձախողումների կամ կլինիկայի չարտոնված օգտագործմամբ առաջացած կորուստների համար։ Այս պայմաններում ոչինչ չի բացառում այն պատասխանատվությունը, որը օրենքով չի կարող բացառվել։ Վեճերի դեպքում նախ պետք է կապվել աջակցության էլ․ փոստով՝ բարեխիղճ լուծում գտնելու նպատակով։",
    ru: "В пределах, допускаемых законом, Teta2 не несет ответственности за клинические решения, пропущенные диагнозы, результаты лечения, сбои сторонних сервисов сообщений или убытки, вызванные несанкционированным использованием клиникой. Ничто в настоящих Условиях не исключает ответственность, которую нельзя законно исключить. Для добросовестного урегулирования спор сначала следует направить на адрес поддержки."
  },
  {
    en: "The public frontend uses browser storage only for essential preferences and session operation.",
    hy: "Հանրային ֆրոնտենդը դիտարկչի պահոցն օգտագործում է միայն անհրաժեշտ կարգավորումների և աշխատաշրջանի աշխատանքի համար։",
    ru: "Публичный фронтенд использует хранилище браузера только для необходимых настроек и работы сессии."
  },
  {
    en: "The current Teta2 frontend does not include Google Analytics, Meta Pixel, PostHog, advertising cookies or cross-site behavioural tracking. Teta2 does not use the essential storage listed above to build advertising profiles.",
    hy: "Teta2-ի ներկայիս ֆրոնտենդը չի ներառում Google Analytics, Meta Pixel, PostHog, գովազդային քուքիներ կամ կայքերի միջև վարքագծային հետևում։ Վերը նշված անհրաժեշտ պահոցը Teta2-ը չի օգտագործում գովազդային պրոֆիլներ ստեղծելու համար։",
    ru: "Текущий фронтенд Teta2 не включает Google Analytics, Meta Pixel, PostHog, рекламные cookie или межсайтовое отслеживание поведения. Teta2 не использует перечисленное выше необходимое хранилище для создания рекламных профилей."
  },
  {
    en: "At expiry, dashboard access is locked rather than the clinic workspace being automatically deleted. Renewal can restore the same clinic workspace and retained records, subject to the Privacy Policy, applicable law and any updated written offer.",
    hy: "Ժամկետի ավարտին վահանակի մուտքը կողպվում է, իսկ կլինիկայի աշխատանքային միջավայրը ինքնաբերաբար չի ջնջվում։ Երկարաձգումը կարող է վերականգնել նույն աշխատանքային միջավայրն ու պահպանված գրառումները՝ Գաղտնիության քաղաքականության, կիրառելի օրենսդրության և ցանկացած թարմացված գրավոր առաջարկի պայմաններով։",
    ru: "По окончании срока доступ к панели блокируется, но рабочее пространство клиники не удаляется автоматически. Продление может восстановить доступ к тому же рабочему пространству и сохраненным записям в соответствии с Политикой конфиденциальности, применимым законодательством и любым обновленным письменным предложением."
  },
  {
    en: "Every image, highlight, label, report, priority or follow-up suggestion must be reviewed by a qualified dental professional together with the original OPG, examination, history and any additional imaging. A user must not treat model output as confirmed disease or absence of disease.",
    hy: "Յուրաքանչյուր պատկեր, նշում, պիտակ, զեկույց, առաջնահերթություն կամ հետագա վերահսկման առաջարկ պետք է վերանայի որակավորված ատամնաբույժը՝ սկզբնական OPG-ի, կլինիկական զննման, պատմության և անհրաժեշտ լրացուցիչ պատկերների հետ միասին։ Օգտատերը չպետք է մոդելի արդյունքը համարի հաստատված հիվանդություն կամ հիվանդության բացակայության ապացույց։",
    ru: "Каждое изображение, выделение, обозначение, отчет, приоритет или рекомендация по последующему наблюдению должны быть проверены квалифицированным стоматологом вместе с исходным OPG, клиническим осмотром, анамнезом и любыми дополнительными снимками. Пользователь не должен считать результат модели подтвержденным заболеванием или доказательством отсутствия заболевания."
  },
  {
    en: "AI can miss findings, mark normal anatomy, localize the wrong tooth or region, misread image artifacts and produce incomplete or incorrect text. Performance can vary with devices, positioning, exposure, anatomy, restorations, pathology and populations. Teta2 does not claim perfect or universally validated diagnostic accuracy.",
    hy: "AI-ը կարող է բաց թողնել փոփոխություններ, սխալ նշել նորմալ անատոմիական կառուցվածքները, սխալ տեղորոշել ատամը կամ շրջանը, սխալ մեկնաբանել պատկերի արտեֆակտները և ստեղծել թերի կամ սխալ տեքստ։ Արդյունավետությունը կարող է տարբերվել սարքից, դիրքավորումից, էքսպոզիցիայից, անատոմիայից, վերականգնումներից, պաթոլոգիայից և պացիենտների խմբերից կախված։ Teta2-ը չի պնդում կատարյալ կամ համընդհանուր վավերացված ախտորոշիչ ճշգրտություն։",
    ru: "ИИ может пропускать изменения, ошибочно отмечать нормальные анатомические структуры, неверно локализовать зуб или область, неправильно интерпретировать артефакты изображения и формировать неполный или ошибочный текст. Результаты могут различаться в зависимости от оборудования, позиционирования, экспозиции, анатомии, реставраций, патологии и популяции. Teta2 не заявляет о безошибочной или универсально валидированной диагностической точности."
  },
  {
    en: "Teta2 is not an emergency service and must not delay urgent assessment. It must not autonomously diagnose, prescribe, select treatment or send clinical claims to a patient without the clinic's appropriate review and authority. The treating clinician remains responsible for the final record and care decision.",
    hy: "Teta2-ը շտապ օգնության ծառայություն չէ և չպետք է հետաձգի հրատապ մասնագիտական գնահատումը։ Այն չպետք է ինքնուրույն ախտորոշի, դեղատոմս նշանակի, ընտրի բուժում կամ պացիենտին ուղարկի կլինիկական պնդումներ՝ առանց կլինիկայի համապատասխան վերանայման և իրավասության։ Բուժող բժիշկը շարունակում է պատասխանատու լինել վերջնական գրառման և բուժման որոշման համար։",
    ru: "Teta2 не является службой экстренной помощи и не должен задерживать срочную профессиональную оценку. Сервис не должен автономно диагностировать, назначать препараты, выбирать лечение или отправлять пациенту клинические утверждения без надлежащей проверки и полномочий клиники. Лечащий врач остается ответственным за итоговую запись и решение о лечении."
  },
  {
    en: "Priorities, schedules and messages support clinic workflow; they do not guarantee patient contact, attendance or outcome. Clinics must verify recipient identity, consent, message accuracy, urgency and suitable escalation. WhatsApp and other delivery services may fail or be unavailable independently of Teta2.",
    hy: "Առաջնահերթությունները, ժամանակացույցերը և հաղորդագրությունները աջակցում են կլինիկայի աշխատանքային գործընթացին, բայց չեն երաշխավորում պացիենտի հետ կապը, այցը կամ կլինիկական արդյունքը։ Կլինիկան պետք է ստուգի ստացողի ինքնությունը, համաձայնությունը, հաղորդագրության ճշգրտությունը, հրատապությունը և անհրաժեշտ էսկալացիան։ WhatsApp-ը և այլ առաքման ծառայություններ կարող են խափանվել կամ անհասանելի լինել Teta2-ից անկախ։",
    ru: "Приоритеты, расписания и сообщения поддерживают рабочий процесс клиники, но не гарантируют контакт с пациентом, явку или клинический результат. Клиника должна проверять личность получателя, согласие, точность сообщения, срочность и необходимость эскалации. WhatsApp и другие сервисы доставки могут дать сбой или быть недоступны независимо от Teta2."
  }
];

const byEnglish = new Map(COPY.map((row) => [row.en, row]));
const originals = new WeakMap<Text, string>();
const outputs = new WeakMap<Text, string>();

function activeLanguage(): Lang | null {
  const value = localStorage.getItem("teta2-product-language") ?? localStorage.getItem("teta2-v4-language") ?? document.documentElement.lang;
  if (value.toLowerCase().startsWith("hy")) return "hy";
  if (value.toLowerCase().startsWith("ru")) return "ru";
  return null;
}

function translateNode(node: Text, lang: Lang): void {
  const current = node.nodeValue ?? "";
  const previous = outputs.get(node);
  if (!originals.has(node) || (previous !== undefined && current !== previous)) originals.set(node, current);
  const source = originals.get(node) ?? current;
  const trimmed = source.trim();
  const row = byEnglish.get(trimmed);
  if (!row) return;
  const translated = row[lang];
  const start = source.indexOf(trimmed);
  const next = `${source.slice(0, start)}${translated}${source.slice(start + trimmed.length)}`;
  if (next !== current) node.nodeValue = next;
  outputs.set(node, next);
}

function apply(root: Node): void {
  const lang = activeLanguage();
  if (!lang) return;
  if (root.nodeType === Node.TEXT_NODE) {
    const parent = (root as Text).parentElement;
    if (parent?.closest(".t2-legal-page")) translateNode(root as Text, lang);
    return;
  }
  if (!(root instanceof Element) && root !== document.body) return;
  const legal = root instanceof Element && root.matches(".t2-legal-page") ? root : (root as Element | HTMLElement).querySelector?.(".t2-legal-page");
  if (!legal) return;
  const walker = document.createTreeWalker(legal, NodeFilter.SHOW_TEXT);
  let node = walker.nextNode();
  while (node) { translateNode(node as Text, lang); node = walker.nextNode(); }
}

export function LegalLocaleQuality() {
  useEffect(() => {
    const refresh = () => window.requestAnimationFrame(() => apply(document.body));
    refresh();
    const observer = new MutationObserver((records) => {
      for (const record of records) for (const node of Array.from(record.addedNodes)) apply(node);
    });
    observer.observe(document.body, { childList: true, subtree: true });
    window.addEventListener("teta2-language-change", refresh);
    window.addEventListener("popstate", refresh);
    return () => {
      observer.disconnect();
      window.removeEventListener("teta2-language-change", refresh);
      window.removeEventListener("popstate", refresh);
    };
  }, []);
  return null;
}
