import { useEffect, useMemo, useRef, useState, type FormEvent, type ReactNode } from "react";
import {
  Activity, ArrowRight, Bell, Building2, CalendarDays, Check, ChevronRight, CircleUserRound,
  FileImage, HeartPulse, Image as ImageIcon, LayoutDashboard, LockKeyhole, LogOut, MessageCircle,
  Plus, Search, Settings, ShieldCheck, Sparkles, UploadCloud, X, type LucideIcon
} from "lucide-react";
import { api, clearSession, errorMessage, hasSession } from "../api/client";
import type { AIAnalysis, CurrentUser, Patient, PatientProfile, Role, XRay } from "../api/types";
import { AnalysisResults } from "../components/AnalysisResults";
import { WhatsAppOutreachCard } from "../components/WhatsAppOutreachCard";
import { c, type Lang } from "./content";
import { v5Api, type BranchRecord, type DashboardRecord, type FollowUpRecord } from "./api";

const LANG_KEY = "teta2-v5-language";
const OPG_HERO_URL = "https://images.squarespace-cdn.com/content/v1/57e01f4c2e69cf3a18c52ac1/09f04224-c53b-4362-aff2-52ae4d2cc114/OPG.jpg";
const publicRoutes = ["/", "/product", "/how-it-works", "/pricing", "/clinical-safety", "/about", "/login", "/register", "/platform", "/ai-workspace", "/smart-recall", "/radar-ai", "/security"] as const;
type PublicRoute = typeof publicRoutes[number];
type AppSection = "dashboard" | "patients" | "analysis" | "followups" | "messages" | "settings";

function getLanguage(): Lang | null {
  const value = localStorage.getItem(LANG_KEY) ?? localStorage.getItem("teta2-v4-language");
  return value === "en" || value === "hy" ? value : null;
}
function fullName(patient: Patient) { return `${patient.first_name} ${patient.last_name}`.trim(); }
function initials(patient: Patient) { return `${patient.first_name[0] ?? ""}${patient.last_name[0] ?? ""}`.toUpperCase(); }
function dateText(value: string | null | undefined, lang: Lang) {
  return value ? new Intl.DateTimeFormat(lang === "hy" ? "hy-AM" : "en-US", { month: "short", day: "numeric", year: "numeric" }).format(new Date(value)) : "—";
}
function roleLabel(role: string, lang: Lang) {
  if (lang === "en") return role.replaceAll("_", " ");
  return ({ DIRECTOR: "Տնօրեն", MANAGER: "Կառավարիչ", DOCTOR: "Բժիշկ" } as Record<string, string>)[role] ?? role;
}
function statusLabel(status: string, lang: Lang) {
  const value = status.toUpperCase();
  if (lang === "en") return value.replaceAll("_", " ");
  return ({
    QUEUED: "Հերթագրված", PROCESSING: "Մշակվում է", COMPLETED: "Ավարտված", FAILED: "Ձախողված",
    PENDING: "Սպասող", CONFIRMED: "Հաստատված", REJECTED: "Մերժված", UNREVIEWED: "Չվերանայված", REVIEWED: "Վերանայված",
    SCHEDULED: "Պլանավորված", DUE: "Ժամկետը հասել է", CANCELLED: "Չեղարկված", ACTIVE: "Ակտիվ"
  } as Record<string, string>)[value] ?? value.replaceAll("_", " ");
}
function normalizedRoute(pathname: string): PublicRoute {
  if (pathname === "/platform" || pathname === "/ai-workspace") return "/product";
  if (pathname === "/smart-recall") return "/how-it-works";
  if (pathname === "/security") return "/clinical-safety";
  if (pathname === "/radar-ai") return "/product";
  return publicRoutes.includes(pathname as PublicRoute) ? pathname as PublicRoute : "/";
}

export default function AppV5() {
  const [lang, setLangState] = useState<Lang | null>(() => getLanguage());
  const [route, setRoute] = useState<PublicRoute>(() => normalizedRoute(window.location.pathname));
  const [user, setUser] = useState<CurrentUser | null>(null);
  const [restoring, setRestoring] = useState(hasSession());

  function setLang(next: Lang) {
    localStorage.setItem(LANG_KEY, next);
    localStorage.setItem("teta2-v4-language", next);
    document.documentElement.lang = next;
    setLangState(next);
  }
  function go(next: PublicRoute) {
    const clean = normalizedRoute(next);
    window.history.pushState({}, "", clean);
    setRoute(clean);
    window.scrollTo({ top: 0, behavior: "smooth" });
  }
  useEffect(() => {
    const pop = () => setRoute(normalizedRoute(window.location.pathname));
    window.addEventListener("popstate", pop);
    return () => window.removeEventListener("popstate", pop);
  }, []);
  useEffect(() => {
    if (lang) document.documentElement.lang = lang;
  }, [lang]);
  useEffect(() => {
    if (!hasSession()) { setRestoring(false); return; }
    api.me().then(setUser).catch(() => clearSession()).finally(() => setRestoring(false));
  }, []);

  if (!lang) return <LanguageGate onSelect={setLang} />;
  if (restoring) return <div className="t5-restore"><Logo /><span className="t5-spinner" /></div>;
  if (user) return <ClinicApp lang={lang} setLang={setLang} user={user} onLogout={() => setUser(null)} />;
  if (route === "/login") return <LoginPage lang={lang} setLang={setLang} go={go} onAuthenticated={setUser} />;
  if (route === "/register") return <RequestAccessPage lang={lang} setLang={setLang} go={go} />;
  return <PublicSite lang={lang} setLang={setLang} route={route} go={go} />;
}

function Logo({ compact = false }: { compact?: boolean }) {
  return <div className={`t5-logo ${compact ? "compact" : ""}`}><span className="t5-logo-mark"><i /><b /></span><strong>Teta2</strong></div>;
}

function LanguageGate({ onSelect }: { onSelect: (lang: Lang) => void }) {
  return <main className="t5-language"><section><Logo/><span className="t5-kicker">WELCOME · ԲԱՐԻ ԳԱԼՈՒՍՏ</span><h1>Choose your language<br/><em>Ընտրեք ձեր լեզուն</em></h1><p>Teta2 supports English and Armenian across the clinic workflow.</p><div><button onClick={()=>onSelect("en")}><b>EN</b><span><strong>English</strong><small>Continue in English</small></span><ChevronRight/></button><button onClick={()=>onSelect("hy")}><b>ՀՅ</b><span><strong>Հայերեն</strong><small>Շարունակել հայերեն</small></span><ChevronRight/></button></div><footer><ShieldCheck size={16}/> Language can be changed later · Լեզուն կարող եք փոխել հետագայում</footer></section></main>;
}

function PublicSite({ lang, setLang, route, go }: { lang: Lang; setLang: (lang: Lang) => void; route: PublicRoute; go: (route: PublicRoute) => void }) {
  return <div className="t5-public"><PublicNav lang={lang} setLang={setLang} route={route} go={go}/><main>{route === "/" && <HomePage lang={lang} go={go}/>} {route === "/product" && <ProductPage lang={lang} go={go}/>} {route === "/how-it-works" && <HowPage lang={lang} go={go}/>} {route === "/pricing" && <PricingPage lang={lang} go={go}/>} {route === "/clinical-safety" && <SafetyPage lang={lang} go={go}/>} {route === "/about" && <AboutPage lang={lang} go={go}/>}</main><PublicFooter lang={lang} go={go}/></div>;
}

function PublicNav({ lang, setLang, route, go }: { lang: Lang; setLang: (lang: Lang) => void; route: PublicRoute; go: (route: PublicRoute) => void }) {
  const copy = c(lang); const links:Array<[PublicRoute,string]>=[["/product",copy.nav.product],["/how-it-works",copy.nav.how],["/pricing",copy.nav.pricing],["/clinical-safety",copy.nav.safety],["/about",copy.nav.about]];
  return <header className="t5-public-nav"><button className="plain" onClick={()=>go("/")}><Logo/></button><nav>{links.map(([path,label])=><button key={path} className={route===path?"active":""} onClick={()=>go(path)}>{label}</button>)}</nav><div className="t5-nav-actions"><button className="text" onClick={()=>go("/login")}>{copy.nav.login}</button><button className="t5-primary small" onClick={()=>go("/register")}>{copy.nav.access}</button><LanguageSwitch lang={lang} setLang={setLang}/></div></header>;
}

function HomePage({ lang, go }: { lang: Lang; go: (route: PublicRoute) => void }) {
  const copy=c(lang); return <>
    <section className="t5-hero"><div className="t5-hero-copy"><span className="t5-pill"><Sparkles size={15}/>{copy.hero.kicker}</span><h1>{copy.hero.title}</h1><p>{copy.hero.lead}</p><div className="t5-hero-actions"><button className="t5-primary" onClick={()=>go("/login")}>{copy.hero.primary}<ArrowRight/></button><button className="t5-secondary" onClick={()=>go("/how-it-works")}>{copy.hero.secondary}</button></div><div className="t5-trust-row"><span><Check/>{copy.hero.trust1}</span><span><Check/>{copy.hero.trust2}</span><span><Check/>{copy.hero.trust3}</span></div></div><OpgProductVisual lang={lang}/></section>
    <ProblemSection lang={lang}/><WorkflowSection lang={lang}/><PlanSection lang={lang} go={go}/><SafetyStrip lang={lang}/><CommercialCTA lang={lang} go={go}/>
  </>;
}

function ProductPage({ lang, go }: { lang: Lang; go: (route: PublicRoute) => void }) {
  const copy=c(lang); return <PageHero kicker={copy.nav.product} title={copy.problem.title} lead={copy.problem.lead}><div className="t5-feature-grid">{copy.problem.cards.map(([title,text],i)=><Feature key={title} icon={i===0?<Sparkles/>:i===1?<CircleUserRound/>:<HeartPulse/>} title={title} text={text}/>)}</div><PlanSection lang={lang} go={go}/><section className="t5-smart-record"><div><span className="t5-kicker">SMART PATIENT FILE</span><h2>{lang==="en"?"Keep the OPG, reviewed findings and follow-up context together.":"Պահեք OPG-ն, վերանայված հայտնաբերումները և հետագա վերահսկման համատեքստը միասին։"}</h2><p>{lang==="en"?"Teta2 is intentionally narrow: imaging intelligence, a smart patient record, and the actions that follow from the radiograph.":"Teta2-ը դիտավորյալ կենտրոնացած է՝ պատկերային ինտելեկտ, խելացի պացիենտի քարտ և ռենտգենից բխող հաջորդ գործողություններ։"}</p></div><SmartFileVisual lang={lang}/></section></PageHero>;
}
function HowPage({ lang, go }: { lang: Lang; go: (route: PublicRoute) => void }) { const copy=c(lang); return <PageHero kicker={copy.workflow.kicker} title={copy.workflow.title} lead={copy.problem.lead}><WorkflowSection lang={lang} embedded/><CommercialCTA lang={lang} go={go}/></PageHero>; }
function SafetyPage({ lang, go }: { lang: Lang; go: (route: PublicRoute) => void }) { const copy=c(lang); return <PageHero kicker={copy.safety.kicker} title={copy.safety.title} lead={copy.safety.lead}><div className="t5-feature-grid safety">{copy.safety.cards.map(([title,text],i)=><Feature key={title} icon={i===0?<ShieldCheck/>:i===1?<LockKeyhole/>:i===2?<Activity/>:<Check/>} title={title} text={text}/>)}</div><div className="t5-safety-notice"><ShieldCheck/><strong>{copy.safety.notice}</strong></div><CommercialCTA lang={lang} go={go}/></PageHero>; }
function AboutPage({ lang, go }: { lang: Lang; go: (route: PublicRoute) => void }) { const copy=c(lang); return <PageHero kicker={copy.about.kicker} title={copy.about.title} lead={copy.about.lead}><div className="t5-principles">{copy.about.principles.map(([title,text],index)=><article key={title}><span>0{index+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div><CommercialCTA lang={lang} go={go}/></PageHero>; }

function PricingPage({ lang, go }: { lang: Lang; go: (route: PublicRoute) => void }) {
  const copy=c(lang); const [market,setMarket]=useState<"am"|"ru">("am"); const [annual,setAnnual]=useState(false);
  const prices=market==="am"?{scan:49000,care:99000,currency:"AMD"}:{scan:4990,care:9990,currency:"RUB"};
  const price=(monthly:number)=>annual?monthly*10:monthly;
  const suffix=annual?copy.pricing.perYear:copy.pricing.perMonth;
  return <PageHero kicker={copy.pricing.kicker} title={copy.pricing.title} lead={copy.pricing.lead}><div className="t5-pricing-controls"><div><button className={market==="am"?"active":""} onClick={()=>setMarket("am")}>{copy.pricing.armenia}</button><button className={market==="ru"?"active":""} onClick={()=>setMarket("ru")}>{copy.pricing.russia}</button></div><div><button className={!annual?"active":""} onClick={()=>setAnnual(false)}>{copy.pricing.monthly}</button><button className={annual?"active":""} onClick={()=>setAnnual(true)}>{copy.pricing.annual}</button></div></div><div className="t5-price-grid"><PriceCard name={copy.plans.scan.name} tagline={copy.plans.scan.tagline} value={price(prices.scan)} currency={prices.currency} suffix={suffix} features={copy.plans.scan.features} outcome={copy.plans.scan.outcome} action={copy.pricing.chooseScan} onClick={()=>go("/register")}/><PriceCard featured name={copy.plans.care.name} tagline={copy.plans.care.tagline} value={price(prices.care)} currency={prices.currency} suffix={suffix} features={copy.plans.care.features} outcome={copy.plans.care.outcome} action={copy.pricing.chooseCare} onClick={()=>go("/register")}/></div><p className="t5-fair-use"><ShieldCheck/>{copy.pricing.unlimited} · {copy.pricing.fairUse}</p></PageHero>;
}

function ProblemSection({ lang }: { lang: Lang }) { const copy=c(lang); return <section className="t5-section"><SectionHead kicker={copy.problem.kicker} title={copy.problem.title} lead={copy.problem.lead}/><div className="t5-feature-grid">{copy.problem.cards.map(([title,text],i)=><Feature key={title} icon={i===0?<Sparkles/>:i===1?<CircleUserRound/>:<HeartPulse/>} title={title} text={text}/>)}</div></section>; }
function WorkflowSection({ lang, embedded=false }: { lang: Lang; embedded?: boolean }) { const copy=c(lang); return <section className={embedded?"t5-workflow embedded":"t5-section t5-workflow"}><SectionHead kicker={copy.workflow.kicker} title={copy.workflow.title}/><div className="t5-workflow-grid">{copy.workflow.steps.map(([n,title,text])=><article key={n}><b>{n}</b><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>; }
function PlanSection({ lang, go }: { lang: Lang; go: (route: PublicRoute) => void }) { const copy=c(lang); return <section className="t5-section t5-plans"><SectionHead kicker={copy.plans.kicker} title={copy.plans.title}/><div className="t5-plan-grid"><PlanCard name={copy.plans.scan.name} tagline={copy.plans.scan.tagline} outcome={copy.plans.scan.outcome} features={copy.plans.scan.features} onClick={()=>go("/pricing")}/><PlanCard care name={copy.plans.care.name} tagline={copy.plans.care.tagline} outcome={copy.plans.care.outcome} features={copy.plans.care.features} onClick={()=>go("/pricing")}/></div></section>; }
function SafetyStrip({ lang }: { lang: Lang }) { const copy=c(lang); return <section className="t5-safety-strip"><ShieldCheck/><div><strong>{copy.safety.title}</strong><p>{copy.safety.notice}</p></div></section>; }
function CommercialCTA({ lang, go }: { lang: Lang; go: (route: PublicRoute) => void }) { const copy=c(lang); return <section className="t5-cta"><Logo/><div><span className="t5-kicker">TETA2</span><h2>{lang==="en"?"Make the OPG the start of the workflow—not the end.":"OPG-ն դարձրեք աշխատանքային հոսքի սկիզբը, ոչ թե վերջը։"}</h2><p>{copy.hero.lead}</p></div><button className="t5-primary" onClick={()=>go("/register")}>{copy.nav.access}<ArrowRight/></button></section>; }

function OpgProductVisual({ lang }: { lang: Lang }) { return <div className="t5-opg-window"><div className="t5-window-bar"><i/><i/><i/><span>Teta2 · {lang==="en"?"OPG Analysis":"OPG վերլուծություն"}</span></div><div className="t5-opg-stage"><img src={OPG_HERO_URL} alt="Panoramic dental radiograph"/><div className="t5-demo-marker m1"><span>16</span></div><div className="t5-demo-marker green m2"><span>24</span></div><div className="t5-demo-marker m3"><span>36</span></div><div className="t5-opg-caption"><strong>{lang==="en"?"Possible findings, visually organized":"Հնարավոր հայտնաբերումներ՝ տեսողական կազմակերպմամբ"}</strong><small>{lang==="en"?"AI-assisted · dentist review required":"AI-ով աջակցվող · պահանջվում է բժշկի վերանայում"}</small></div></div></div>; }
function SmartFileVisual({ lang }: { lang: Lang }) { return <div className="t5-file-visual"><header><span>TP</span><div><strong>{lang==="en"?"Patient record":"Պացիենտի քարտ"}</strong><small>OPG · AI · Follow-up</small></div></header><div className="t5-file-timeline"><i/><article><b>{lang==="en"?"OPG uploaded":"OPG վերբեռնված"}</b><small>Sep 08</small></article><i/><article><b>{lang==="en"?"Possible findings reviewed":"Հնարավոր հայտնաբերումները վերանայված են"}</b><small>{lang==="en"?"Clinician confirmed":"Բժշկի կողմից հաստատված"}</small></article><i/><article><b>{lang==="en"?"Follow-up action":"Հետագա գործողություն"}</b><small>Care</small></article></div></div>; }
function PageHero({ kicker,title,lead,children }: { kicker:string; title:string; lead:string; children:ReactNode }) { return <><section className="t5-page-hero"><span className="t5-pill"><Sparkles size={14}/>{kicker}</span><h1>{title}</h1><p>{lead}</p></section><section className="t5-section page">{children}</section></>; }
function SectionHead({ kicker,title,lead }: { kicker:string; title:string; lead?:string }) { return <div className="t5-section-head"><span>{kicker}</span><h2>{title}</h2>{lead&&<p>{lead}</p>}</div>; }
function Feature({ icon,title,text }: { icon:ReactNode; title:string; text:string }) { return <article className="t5-feature"><span>{icon}</span><h3>{title}</h3><p>{text}</p></article>; }
function PlanCard({ name,tagline,outcome,features,care=false,onClick }: { name:string; tagline:string; outcome:string; features:readonly string[]; care?:boolean; onClick:()=>void }) { return <article className={`t5-plan ${care?"care":""}`}><span className="t5-plan-label">{care?"CARE":"SCAN"}</span><h3>{name}</h3><p>{tagline}</p><strong>{outcome}</strong><ul>{features.slice(0,6).map(item=><li key={item}><Check/>{item}</li>)}</ul><button onClick={onClick}>Explore plan <ArrowRight/></button></article>; }
function PriceCard({ name,tagline,value,currency,suffix,features,outcome,action,onClick,featured=false }: { name:string; tagline:string; value:number; currency:string; suffix:string; features:readonly string[]; outcome:string; action:string; onClick:()=>void; featured?:boolean }) { return <article className={`t5-price-card ${featured?"featured":""}`}>{featured&&<span className="t5-recommended">CARE</span>}<h3>{name}</h3><p>{tagline}</p><div className="t5-price"><strong>{new Intl.NumberFormat("en-US").format(value)}</strong><span>{currency}<small>{suffix}</small></span></div><em>{outcome}</em><ul>{features.map(item=><li key={item}><Check/>{item}</li>)}</ul><button className={featured?"t5-primary":"t5-secondary"} onClick={onClick}>{action}<ArrowRight/></button></article>; }

function PublicFooter({ lang, go }: { lang:Lang; go:(route:PublicRoute)=>void }) { const copy=c(lang); return <footer className="t5-footer"><div><Logo/><p>{copy.brand.tagline}</p></div><div><button onClick={()=>go("/product")}>{copy.nav.product}</button><button onClick={()=>go("/how-it-works")}>{copy.nav.how}</button><button onClick={()=>go("/pricing")}>{copy.nav.pricing}</button></div><div><button onClick={()=>go("/clinical-safety")}>{copy.nav.safety}</button><button onClick={()=>go("/about")}>{copy.nav.about}</button><button onClick={()=>go("/login")}>{copy.nav.login}</button></div><small>© 2026 Teta2 · AI-assisted OPG intelligence · Possible findings require dentist examination.</small></footer>; }
function LanguageSwitch({lang,setLang}:{lang:Lang;setLang:(lang:Lang)=>void}) { return <div className="t5-lang"><button className={lang==="en"?"active":""} onClick={()=>setLang("en")}>EN</button><button className={lang==="hy"?"active":""} onClick={()=>setLang("hy")}>HY</button></div>; }

function LoginPage({ lang,setLang,go,onAuthenticated }:{lang:Lang;setLang:(lang:Lang)=>void;go:(route:PublicRoute)=>void;onAuthenticated:(user:CurrentUser)=>void}) {
  const copy=c(lang); const [slug,setSlug]=useState("");const[identifier,setIdentifier]=useState("");const[password,setPassword]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{await api.login({clinic_slug:slug.trim().toLowerCase(),identifier:identifier.trim(),password});onAuthenticated(await api.me())}catch(reason){clearSession();setError(errorMessage(reason))}finally{setBusy(false)}}
  return <main className="t5-auth"><section className="t5-auth-story"><button className="plain" onClick={()=>go("/")}><Logo/></button><span className="t5-pill"><ShieldCheck size={14}/>{c(lang).brand.tagline}</span><h1>{copy.auth.loginTitle}</h1><p>{copy.auth.loginLead}</p><div className="t5-auth-flow"><span>OPG</span><ArrowRight/><span>AI</span><ArrowRight/><span>{lang==="en"?"Review":"Վերանայում"}</span><ArrowRight/><span>{lang==="en"?"Follow-up":"Հետևում"}</span></div></section><section className="t5-auth-card"><LanguageSwitch lang={lang} setLang={setLang}/><h2>{copy.auth.loginTitle}</h2><form onSubmit={submit}><label>{copy.auth.slug}<input required value={slug} onChange={e=>setSlug(e.target.value.toLowerCase())} autoComplete="organization" placeholder="clinic-slug"/></label><label>{copy.auth.identifier}<input required value={identifier} onChange={e=>setIdentifier(e.target.value)} autoComplete="username"/></label><label>{copy.auth.password}<input required type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label>{error&&<div className="t5-error">{error}</div>}<button className="t5-primary wide" disabled={busy}>{busy?copy.auth.submitting:copy.auth.submit}</button></form><button className="t5-link-button" onClick={()=>go("/register")}>{c(lang).nav.access}<ArrowRight/></button></section></main>;
}
function RequestAccessPage({ lang,setLang,go }:{lang:Lang;setLang:(lang:Lang)=>void;go:(route:PublicRoute)=>void}) { const copy=c(lang); const [plan,setPlan]=useState<"scan"|"care">("care");const[market,setMarket]=useState<"am"|"ru">("am");return <main className="t5-auth"><section className="t5-auth-story"><button className="plain" onClick={()=>go("/")}><Logo/></button><span className="t5-pill"><Building2 size={14}/>{copy.auth.activation}</span><h1>{copy.auth.requestTitle}</h1><p>{copy.auth.requestLead}</p><div className="t5-request-summary"><strong>{plan==="scan"?copy.plans.scan.name:copy.plans.care.name}</strong><span>{market==="am"?copy.pricing.armenia:copy.pricing.russia}</span><small>{plan==="scan"?copy.plans.scan.outcome:copy.plans.care.outcome}</small></div></section><section className="t5-auth-card"><LanguageSwitch lang={lang} setLang={setLang}/><h2>{copy.auth.activation}</h2><p className="t5-muted">{copy.auth.activationCopy}</p><label>{copy.auth.plan}<select value={plan} onChange={e=>setPlan(e.target.value as "scan"|"care")}><option value="scan">{copy.plans.scan.name}</option><option value="care">{copy.plans.care.name}</option></select></label><label>{copy.auth.market}<select value={market} onChange={e=>setMarket(e.target.value as "am"|"ru")}><option value="am">{copy.pricing.armenia}</option><option value="ru">{copy.pricing.russia}</option></select></label><div className="t5-onboarding-note"><ShieldCheck/><p>{copy.auth.requestLead}</p></div><button className="t5-secondary wide" onClick={()=>go("/login")}>{copy.auth.existing}</button></section></main>}

function ClinicApp({lang,setLang,user,onLogout}:{lang:Lang;setLang:(lang:Lang)=>void;user:CurrentUser;onLogout:()=>void}) {
  const copy=c(lang).app; const [section,setSection]=useState<AppSection>("dashboard"); const [patients,setPatients]=useState<Patient[]>([]); const [profiles,setProfiles]=useState<Record<string,PatientProfile>>({}); const [branches,setBranches]=useState<BranchRecord[]>([]); const [dashboard,setDashboard]=useState<DashboardRecord>({}); const [followups,setFollowups]=useState<FollowUpRecord[]>([]); const [selectedPatientId,setSelectedPatientId]=useState(""); const [selectedXrayId,setSelectedXrayId]=useState(""); const [selectedAnalysisId,setSelectedAnalysisId]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [patientModal,setPatientModal]=useState(false); const poll=useRef<number|null>(null);
  const profile=selectedPatientId?profiles[selectedPatientId]??null:null;
  async function loadProfile(id:string){const result=await api.patientProfile(id);setProfiles(current=>({...current,[id]:result}));return result}
  async function refreshPatients(){const page=await api.listPatients();setPatients(page.items);const loaded=await Promise.allSettled(page.items.slice(0,12).map(item=>api.patientProfile(item.id)));const map:Record<string,PatientProfile>={};loaded.forEach(result=>{if(result.status==="fulfilled")map[result.value.patient.id]=result.value});setProfiles(current=>({...current,...map}));}
  async function refreshOperational(){const [dash,branchRows,followRows]=await Promise.allSettled([v5Api.dashboard(user.role),v5Api.branches(),v5Api.listFollowUps()]);if(dash.status==="fulfilled")setDashboard(dash.value);if(branchRows.status==="fulfilled")setBranches(branchRows.value);if(followRows.status==="fulfilled")setFollowups(followRows.value.items)}
  useEffect(()=>{Promise.all([refreshPatients(),refreshOperational()]).catch(reason=>setError(errorMessage(reason)));return()=>{if(poll.current)window.clearTimeout(poll.current)}},[]);
  async function openPatient(id:string,destination:AppSection=section){setSelectedPatientId(id);setSection(destination);setBusy(true);try{const next=profiles[id]??await loadProfile(id);const analysis=next.ai_analyses[0];setSelectedAnalysisId(analysis?.id??"");setSelectedXrayId(analysis?.xray_id??next.xrays[0]?.id??"")}catch(reason){setError(errorMessage(reason))}finally{setBusy(false)}}
  async function upload(file:File){if(!profile)return;setBusy(true);setError("");try{const xray=await api.uploadXray(profile.patient.id,file);setSelectedXrayId(xray.id);await loadProfile(profile.patient.id)}catch(reason){setError(errorMessage(reason))}finally{setBusy(false)}}
  async function runAnalysis(){if(!profile||!selectedXrayId)return;setBusy(true);setError("");try{const analysis=await api.createAnalysis(selectedXrayId);setSelectedAnalysisId(analysis.id);await loadProfile(profile.patient.id);pollAnalysis(profile.patient.id,analysis.id)}catch(reason){setError(errorMessage(reason))}finally{setBusy(false)}}
  function pollAnalysis(patientId:string,analysisId:string,attempt=0){if(attempt>150)return;poll.current=window.setTimeout(async()=>{try{const next=await loadProfile(patientId);const analysis=next.ai_analyses.find(item=>item.id===analysisId);if(analysis&&["QUEUED","PROCESSING"].includes(analysis.status))pollAnalysis(patientId,analysisId,attempt+1);else await refreshOperational()}catch{pollAnalysis(patientId,analysisId,attempt+1)}},2000)}
  function patientUpdated(next:Patient){setPatients(items=>items.map(item=>item.id===next.id?next:item));setProfiles(current=>current[next.id]?{...current,[next.id]:{...current[next.id],patient:next}}:current)}
  async function logout(){try{await api.logout()}finally{onLogout()}}
  const nav:Array<[AppSection,string,LucideIcon]>=[["dashboard",copy.nav.dashboard,LayoutDashboard],["patients",copy.nav.patients,CircleUserRound],["analysis",copy.nav.analysis,Sparkles],["followups",copy.nav.followups,CalendarDays],["messages",copy.nav.messages,MessageCircle],["settings",copy.nav.settings,Settings]];
  return <div className="t5-app"><aside className="t5-sidebar"><div className="t5-sidebar-brand"><Logo/><small>{c(lang).brand.tagline}</small></div><nav>{nav.map(([id,label,Icon])=><button key={id} className={section===id?"active":""} onClick={()=>setSection(id)}><Icon/>{label}</button>)}</nav><div className="t5-sidebar-user"><span>{user.username.slice(0,2).toUpperCase()}</span><div><strong>{user.username}</strong><small>{roleLabel(user.role,lang)}</small></div><button onClick={()=>void logout()}><LogOut/></button></div></aside><header className="t5-app-top"><div><span>{copy.greeting}</span><h1>{nav.find(([id])=>id===section)?.[1]}</h1><p>{copy.subtitle}</p></div><div className="t5-app-top-actions"><span><Building2/>{user.branch_scope.length}</span><LanguageSwitch lang={lang} setLang={setLang}/><button className="t5-icon-button"><Bell/></button></div></header><main className="t5-app-main">{busy&&<div className="t5-progress"/>}{error&&<div className="t5-error global">{error}<button onClick={()=>setError("")}><X/></button></div>}{section==="dashboard"&&<DashboardPage lang={lang} user={user} patients={patients} profiles={profiles} dashboard={dashboard} followups={followups} openPatient={openPatient}/>} {section==="patients"&&<PatientsPage lang={lang} user={user} patients={patients} profiles={profiles} profile={profile} branches={branches} openPatient={openPatient} onAdd={()=>setPatientModal(true)}/>} {section==="analysis"&&<AnalysisPage lang={lang} role={user.role} patients={patients} profile={profile} selectedPatientId={selectedPatientId} selectedXrayId={selectedXrayId} selectedAnalysisId={selectedAnalysisId} openPatient={openPatient} upload={upload} runAnalysis={runAnalysis} refreshProfile={loadProfile} setSelectedXrayId={setSelectedXrayId} setSelectedAnalysisId={setSelectedAnalysisId}/>} {section==="followups"&&<FollowupsPage lang={lang} patients={patients} followups={followups} setFollowups={setFollowups} openPatient={openPatient}/>} {section==="messages"&&<MessagesPage lang={lang} patients={patients} profile={profile} selectedPatientId={selectedPatientId} openPatient={openPatient} onPatientUpdated={patientUpdated}/>} {section==="settings"&&<SettingsPage lang={lang} user={user}/>}</main>{patientModal&&<PatientModal lang={lang} branches={branches} onClose={()=>setPatientModal(false)} onCreated={async patient=>{setPatientModal(false);await refreshPatients();await refreshOperational();await openPatient(patient.id,"patients")}}/>}</div>;
}

function DashboardPage({lang,user,patients,profiles,dashboard,followups,openPatient}:{lang:Lang;user:CurrentUser;patients:Patient[];profiles:Record<string,PatientProfile>;dashboard:DashboardRecord;followups:FollowUpRecord[];openPatient:(id:string,d?:AppSection)=>Promise<void>}) {
  const copy=c(lang).app; const analyses=Object.values(profiles).flatMap(profile=>profile.ai_analyses.map(analysis=>({analysis,patient:profile.patient}))).sort((a,b)=>new Date(b.analysis.requested_at).getTime()-new Date(a.analysis.requested_at).getTime()).slice(0,5); const due=followups.filter(item=>item.status==="DUE").length;
  const dashboardPatient=Number(dashboard.patient_count??dashboard.authorized_patient_count??dashboard.assigned_patient_count??patients.length);const analysisCount=Number(dashboard.ai_analysis_count??Object.values(profiles).reduce((sum,p)=>sum+p.ai_analyses.length,0));const followCount=Number(dashboard.followup_count??followups.length);const doctorCount=Number(dashboard.doctor_count??dashboard.authorized_doctor_count??0);const branchCount=Number(dashboard.branch_count??user.branch_scope.length);
  return <Module title={copy.dashboardTitle} lead={copy.dashboardLead}><div className="t5-metrics"><Metric icon={<CircleUserRound/>} label={copy.metrics.patients} value={dashboardPatient}/><Metric icon={<Sparkles/>} label={copy.metrics.analyses} value={analysisCount}/><Metric icon={<CalendarDays/>} label={copy.metrics.followups} value={followCount}/><Metric icon={<Activity/>} label={copy.metrics.due} value={Number(dashboard.followups_due??due)}/><Metric icon={<Building2/>} label={copy.metrics.branches} value={branchCount}/><Metric icon={<HeartPulse/>} label={copy.metrics.doctors} value={doctorCount}/></div><div className="t5-dashboard-columns"><section className="t5-card"><CardHead title={lang==="en"?"Recent patients":"Վերջին պացիենտներ"} count={patients.length}/>{patients.slice(0,6).map(patient=><button className="t5-row" key={patient.id} onClick={()=>void openPatient(patient.id,"patients")}><span className="t5-avatar">{initials(patient)}</span><div><strong>{fullName(patient)}</strong><small>{patient.patient_number}</small></div><ChevronRight/></button>)}</section><section className="t5-card"><CardHead title={lang==="en"?"Recent OPG analyses":"Վերջին OPG վերլուծություններ"} count={analyses.length}/>{analyses.map(({analysis,patient})=><button className="t5-row" key={analysis.id} onClick={()=>void openPatient(patient.id,"analysis")}><span className="t5-analysis-icon"><Sparkles/></span><div><strong>{fullName(patient)}</strong><small>{dateText(analysis.requested_at,lang)}</small></div><Status value={analysis.status} lang={lang}/></button>)}</section><section className="t5-card wide"><CardHead title={copy.followTitle} count={followups.length}/>{followups.slice(0,8).map(item=><FollowUpRow key={item.id} lang={lang} item={item} patient={patients.find(patient=>patient.id===item.patient_id)} onClick={()=>void openPatient(item.patient_id,"followups")}/>)}</section></div><div className="t5-clinical-notice"><ShieldCheck/><strong>{copy.clinicianNotice}</strong></div></Module>;
}

function PatientsPage({lang,user,patients,profiles,profile,branches,openPatient,onAdd}:{lang:Lang;user:CurrentUser;patients:Patient[];profiles:Record<string,PatientProfile>;profile:PatientProfile|null;branches:BranchRecord[];openPatient:(id:string,d?:AppSection)=>Promise<void>;onAdd:()=>void}) {
  const copy=c(lang).app; return <Module title={copy.patientTitle} lead={copy.patientLead} action={(user.role==="DIRECTOR"||user.role==="MANAGER")?<button className="t5-primary small" onClick={onAdd}><Plus/>{copy.addPatient}</button>:undefined}><div className="t5-patient-layout"><section className="t5-card t5-patient-list"><label className="t5-search"><Search/><input placeholder={copy.selectPatient}/></label>{patients.map(patient=>{const p=profiles[patient.id];return <button className={profile?.patient.id===patient.id?"active t5-row":"t5-row"} key={patient.id} onClick={()=>void openPatient(patient.id,"patients")}><span className="t5-avatar">{initials(patient)}</span><div><strong>{fullName(patient)}</strong><small>{patient.patient_number} · {p?.xrays.length??0} OPG · {p?.findings.length??0} findings</small></div><ChevronRight/></button>})}</section>{profile?<SmartPatientFile lang={lang} profile={profile} branches={branches} onOpenAnalysis={()=>void openPatient(profile.patient.id,"analysis")} onOpenMessages={()=>void openPatient(profile.patient.id,"messages")}/>:<section className="t5-card t5-empty-large"><CircleUserRound/><h3>{copy.noPatient}</h3></section>}</div></Module>;
}
function SmartPatientFile({lang,profile,branches,onOpenAnalysis,onOpenMessages}:{lang:Lang;profile:PatientProfile;branches:BranchRecord[];onOpenAnalysis:()=>void;onOpenMessages:()=>void}) { const latestAnalysis=profile.ai_analyses[0]; const latestXray=profile.xrays[0]; const pending=profile.findings.filter(item=>item.review_status==="PENDING").length; const branch=branches.find(item=>item.id===profile.patient.branch_id); return <section className="t5-smart-file"><header><div className="t5-avatar large">{initials(profile.patient)}</div><div><span className="t5-kicker">SMART PATIENT FILE</span><h2>{fullName(profile.patient)}</h2><p>{profile.patient.patient_number} · {branch?.name??profile.patient.branch_id}</p></div><Status value={profile.patient.status} lang={lang}/></header><div className="t5-file-metrics"><Metric label={lang==="en"?"OPGs":"OPG-ներ"} value={profile.xrays.length}/><Metric label={lang==="en"?"Analyses":"Վերլուծություններ"} value={profile.ai_analyses.length}/><Metric label={lang==="en"?"Possible findings":"Հնարավոր հայտնաբերումներ"} value={profile.findings.length}/><Metric label={lang==="en"?"Pending review":"Սպասող վերանայում"} value={pending}/></div><div className="t5-file-sections"><article><span><ImageIcon/></span><div><small>{lang==="en"?"Latest OPG":"Վերջին OPG"}</small><strong>{latestXray?.original_filename??"—"}</strong><em>{dateText(latestXray?.uploaded_at,lang)}</em></div><button onClick={onOpenAnalysis}>{lang==="en"?"Open":"Բացել"}<ArrowRight/></button></article><article><span><Sparkles/></span><div><small>{lang==="en"?"Latest analysis":"Վերջին վերլուծություն"}</small><strong>{latestAnalysis?statusLabel(latestAnalysis.status,lang):"—"}</strong><em>{dateText(latestAnalysis?.completed_at??latestAnalysis?.requested_at,lang)}</em></div><button onClick={onOpenAnalysis}>{lang==="en"?"Review":"Վերանայել"}<ArrowRight/></button></article><article><span><CalendarDays/></span><div><small>{lang==="en"?"Follow-up history":"Հետագա վերահսկման պատմություն"}</small><strong>{profile.followups.length}</strong><em>{lang==="en"?"timeline items":"ժամանակացույցի գրառում"}</em></div></article><article><span><MessageCircle/></span><div><small>WhatsApp</small><strong>{profile.patient.whatsapp_phone??"—"}</strong><em>{profile.patient.email??profile.patient.phone??"—"}</em></div><button onClick={onOpenMessages}>{lang==="en"?"Messages":"Հաղորդագրություններ"}<ArrowRight/></button></article></div></section> }

function AnalysisPage({lang,role,patients,profile,selectedPatientId,selectedXrayId,selectedAnalysisId,openPatient,upload,runAnalysis,refreshProfile,setSelectedXrayId,setSelectedAnalysisId}:{lang:Lang;role:Role;patients:Patient[];profile:PatientProfile|null;selectedPatientId:string;selectedXrayId:string;selectedAnalysisId:string;openPatient:(id:string,d?:AppSection)=>Promise<void>;upload:(file:File)=>Promise<void>;runAnalysis:()=>Promise<void>;refreshProfile:(id:string)=>Promise<PatientProfile>;setSelectedXrayId:(id:string)=>void;setSelectedAnalysisId:(id:string)=>void}) {
  const copy=c(lang).app;const ref=useRef<HTMLInputElement|null>(null);const selectedAnalysis=profile?.ai_analyses.find(item=>item.id===selectedAnalysisId)??null;const xray=selectedAnalysis?profile?.xrays.find(item=>item.id===selectedAnalysis.xray_id)??null:null;const findings=profile?.findings.filter(item=>item.analysis_id===selectedAnalysisId)??[];
  return <Module title={copy.opgTitle} lead={copy.opgLead}><div className="t5-analysis-toolbar"><PatientSelect lang={lang} patients={patients} value={selectedPatientId} onChange={id=>void openPatient(id,"analysis")}/>{profile&&<><select value={selectedXrayId} onChange={e=>setSelectedXrayId(e.target.value)}><option value="">{copy.selectOpg}</option>{profile.xrays.map(item=><option key={item.id} value={item.id}>{item.original_filename} · {dateText(item.uploaded_at,lang)}</option>)}</select><input ref={ref} hidden type="file" accept="image/jpeg,image/png,image/webp,application/dicom" onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file)}}/><button className="t5-secondary" onClick={()=>ref.current?.click()}><UploadCloud/>{copy.upload}</button><button className="t5-primary" disabled={!selectedXrayId||role!=="DOCTOR"} onClick={()=>void runAnalysis()}><Sparkles/>{copy.run}</button></>}</div>{profile&&profile.ai_analyses.length>0&&<div className="t5-analysis-history"><span>{lang==="en"?"Analysis history":"Վերլուծությունների պատմություն"}</span>{profile.ai_analyses.slice(0,10).map(item=><button key={item.id} className={selectedAnalysisId===item.id?"active":""} onClick={()=>{setSelectedAnalysisId(item.id);setSelectedXrayId(item.xray_id)}}><Status value={item.status} lang={lang}/><small>{dateText(item.requested_at,lang)}</small></button>)}</div>}{!profile&&<div className="t5-empty-large"><ImageIcon/><h3>{copy.noPatient}</h3></div>}{profile&&profile.xrays.length===0&&<div className="t5-empty-large"><FileImage/><h3>{copy.noOpg}</h3><button className="t5-primary" onClick={()=>ref.current?.click()}>{copy.upload}</button></div>}{profile&&selectedAnalysis&&<section className="t5-analysis-results"><AnalysisResults analysis={selectedAnalysis} xray={xray} findings={findings} role={role} onReviewed={()=>refreshProfile(profile.patient.id)}/></section>}</Module>;
}

function FollowupsPage({lang,patients,followups,setFollowups,openPatient}:{lang:Lang;patients:Patient[];followups:FollowUpRecord[];setFollowups:(items:FollowUpRecord[])=>void;openPatient:(id:string,d?:AppSection)=>Promise<void>}) { const copy=c(lang).app;const[filter,setFilter]=useState("ALL");const[busy,setBusy]=useState("");const visible=filter==="ALL"?followups:followups.filter(item=>item.status===filter);async function complete(item:FollowUpRecord){setBusy(item.id);try{const next=await v5Api.updateFollowUp(item.id,"COMPLETED");setFollowups(followups.map(row=>row.id===item.id?next:row))}finally{setBusy("")}}return <Module title={copy.followTitle} lead={copy.followLead}><div className="t5-filter-tabs">{[["ALL",copy.all],["SCHEDULED",copy.scheduled],["DUE",copy.dueStatus],["COMPLETED",copy.completed],["CANCELLED",copy.cancelled]].map(([value,label])=><button key={value} className={filter===value?"active":""} onClick={()=>setFilter(value)}>{label}</button>)}</div><section className="t5-card t5-follow-list">{visible.map(item=><div className="t5-follow-row" key={item.id}><button className="t5-follow-main" onClick={()=>void openPatient(item.patient_id,"patients")}><span className={`t5-priority ${item.priority.toLowerCase()}`}>{item.priority}</span><div><strong>{patients.find(patient=>patient.id===item.patient_id)?fullName(patients.find(patient=>patient.id===item.patient_id)!):item.patient_id}</strong><p>{item.reason}</p></div><time>{dateText(item.due_at,lang)}</time><Status value={item.status} lang={lang}/></button>{item.status!=="COMPLETED"&&item.status!=="CANCELLED"&&<button className="t5-complete" disabled={busy===item.id} onClick={()=>void complete(item)}><Check/>{copy.markCompleted}</button>}</div>)}{visible.length===0&&<div className="t5-empty">{copy.noFollowups}</div>}</section></Module> }
function MessagesPage({lang,patients,profile,selectedPatientId,openPatient,onPatientUpdated}:{lang:Lang;patients:Patient[];profile:PatientProfile|null;selectedPatientId:string;openPatient:(id:string,d?:AppSection)=>Promise<void>;onPatientUpdated:(patient:Patient)=>void}) { const copy=c(lang).app;return <Module title={copy.messagesTitle} lead={copy.messagesLead}><PatientSelect lang={lang} patients={patients} value={selectedPatientId} onChange={id=>void openPatient(id,"messages")}/>{profile?<div className="t5-message-layout"><div className="v4-outreach-tool"><WhatsAppOutreachCard patient={profile.patient} onPatientUpdated={onPatientUpdated}/></div><section className="t5-card"><CardHead title={fullName(profile.patient)} count={profile.followups.length}/><dl className="t5-details"><div><dt>WhatsApp</dt><dd>{profile.patient.whatsapp_phone??"—"}</dd></div><div><dt>{lang==="en"?"Phone":"Հեռախոս"}</dt><dd>{profile.patient.phone??"—"}</dd></div><div><dt>Email</dt><dd>{profile.patient.email??"—"}</dd></div><div><dt>{lang==="en"?"Follow-ups":"Հետագա վերահսկումներ"}</dt><dd>{profile.followups.length}</dd></div></dl></section></div>:<div className="t5-empty-large"><MessageCircle/><h3>{copy.choosePatientMessage}</h3></div>}</Module> }
function SettingsPage({lang,user}:{lang:Lang;user:CurrentUser}) { const copy=c(lang).app;const[health,setHealth]=useState("checking");useEffect(()=>{api.ready().then(()=>setHealth("ready")).catch(()=>setHealth("unavailable"))},[]);return <Module title={copy.settingsTitle} lead={copy.settingsLead}><div className="t5-settings"><section className="t5-card"><ShieldCheck/><h3>{lang==="en"?"Authenticated clinic context":"Նույնականացված կլինիկական համատեքստ"}</h3><dl className="t5-details"><div><dt>{copy.clinicId}</dt><dd>{user.clinic_id}</dd></div><div><dt>{copy.role}</dt><dd>{roleLabel(user.role,lang)}</dd></div><div><dt>{copy.branchScope}</dt><dd>{user.branch_scope.length}</dd></div></dl></section><section className="t5-card"><Activity/><h3>{copy.backend}</h3><Status value={health==="ready"?"READY":"FAILED"} lang={lang}/><p>{health==="ready"?copy.ready:copy.unavailable}</p></section></div></Module> }

function PatientModal({lang,branches,onClose,onCreated}:{lang:Lang;branches:BranchRecord[];onClose:()=>void;onCreated:(patient:Patient)=>void|Promise<void>}) { const copy=c(lang).app;const[number,setNumber]=useState("");const[first,setFirst]=useState("");const[last,setLast]=useState("");const[branch,setBranch]=useState(branches[0]?.id??"");const[busy,setBusy]=useState(false);const[error,setError]=useState("");async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{const patient=await v5Api.createPatient({patient_number:number.trim(),first_name:first.trim(),last_name:last.trim(),branch_id:branch});await onCreated(patient)}catch(reason){setError(errorMessage(reason))}finally{setBusy(false)}}return <div className="t5-modal-backdrop"><section className="t5-modal"><button className="t5-modal-close" onClick={onClose}><X/></button><span className="t5-kicker">SMART PATIENT FILE</span><h2>{copy.addPatient}</h2><form onSubmit={submit}><label>{copy.patientNumber}<input required value={number} onChange={e=>setNumber(e.target.value)}/></label><div className="t5-form-two"><label>{copy.firstName}<input required value={first} onChange={e=>setFirst(e.target.value)}/></label><label>{copy.lastName}<input required value={last} onChange={e=>setLast(e.target.value)}/></label></div><label>{copy.branch}<select required value={branch} onChange={e=>setBranch(e.target.value)}><option value="">—</option>{branches.filter(item=>item.is_active!==false).map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label>{error&&<div className="t5-error">{error}</div>}<div className="t5-modal-actions"><button type="button" className="t5-secondary" onClick={onClose}>{copy.cancel}</button><button className="t5-primary" disabled={busy||!branch}>{copy.create}</button></div></form></section></div> }

function Module({title,lead,action,children}:{title:string;lead:string;action?:ReactNode;children:ReactNode}) { return <div className="t5-module"><header><div><span className="t5-kicker">TETA2</span><h2>{title}</h2><p>{lead}</p></div>{action}</header>{children}</div>; }
function PatientSelect({lang,patients,value,onChange}:{lang:Lang;patients:Patient[];value:string;onChange:(id:string)=>void}) { return <label className="t5-patient-select"><Search/><select value={value} onChange={e=>onChange(e.target.value)}><option value="">{c(lang).app.selectPatient}</option>{patients.map(patient=><option key={patient.id} value={patient.id}>{fullName(patient)} · {patient.patient_number}</option>)}</select></label>; }
function Metric({label,value,icon}:{label:string;value:unknown;icon?:ReactNode}) { return <article className="t5-metric">{icon&&<span>{icon}</span>}<div><small>{label}</small><strong>{typeof value==="number"||typeof value==="string"?String(value):"—"}</strong></div></article>; }
function CardHead({title,count}:{title:string;count:number}) { return <div className="t5-card-head"><h3>{title}</h3><span>{count}</span></div>; }
function Status({value,lang}:{value:string;lang:Lang}) { return <span className={`t5-status ${value.toLowerCase().replaceAll("_","-")}`}>{statusLabel(value,lang)}</span>; }
function FollowUpRow({lang,item,patient,onClick}:{lang:Lang;item:FollowUpRecord;patient?:Patient;onClick:()=>void}) { return <button className="t5-follow-mini" onClick={onClick}><span className={`t5-priority ${item.priority.toLowerCase()}`}>{item.priority}</span><div><strong>{patient?fullName(patient):item.patient_id}</strong><small>{item.reason}</small></div><time>{dateText(item.due_at,lang)}</time><Status value={item.status} lang={lang}/></button>; }
