export type Lang = "en" | "hy";

export const languageMeta: Record<Lang, { label: string; native: string; locale: string }> = {
  en: { label: "English", native: "English", locale: "en-US" },
  hy: { label: "Armenian", native: "Հայերեն", locale: "hy-AM" }
};

export const copy = {
  en: {
    language: { title: "Choose your language", subtitle: "Teta2 will use this language across the entire platform.", english: "English", armenian: "Հայերեն", continue: "Continue" },
    brand: { tagline: "Teeth Evaluation & Treatment AI Assistant", platform: "AI Dental Platform" },
    public: {
      nav: { product: "Product", workflow: "Workflow", radar: "Radar AI", security: "Security", login: "Sign in", register: "Start for your clinic" },
      badge: "Clinical AI for modern dental teams",
      heroTitleA: "See more in every OPG.", heroTitleB: "Remember every tooth. Bring patients back.",
      heroCopy: "Teta2 turns panoramic dental imaging into an intelligent longitudinal record—helping clinicians review AI findings, preserve tooth-level history, plan follow-ups, and identify new treatment demand with Radar AI.",
      heroPrimary: "Start clinic onboarding", heroSecondary: "Open clinic dashboard",
      proof1: "9 specialized ONNX models", proof2: "Private X-ray storage", proof3: "Clinician review required",
      sectionKicker: "One operating layer for intelligent dentistry", sectionTitle: "Clinical intelligence, patient continuity, and growth in one platform.",
      feature1Title: "OPG Clinical Intelligence", feature1Copy: "Review tooth-level AI findings in context, keep evidence attached to the patient, and confirm every finding clinically.",
      feature2Title: "Smart Recall", feature2Copy: "Turn clinical findings into a living care timeline with follow-up logic and structured outreach for future visits.",
      feature3Title: "Radar AI", feature3Copy: "Surface relevant social demand, rank opportunities, and give the clinic team a focused queue for outreach.",
      workflowKicker: "From image to continuity", workflowTitle: "A workflow designed around the dentist—not the model.",
      securityKicker: "Built for clinical trust", securityTitle: "Private by design. Human-reviewed by default.",
      ctaTitle: "Give your clinic an intelligent second layer.", ctaCopy: "Start with one branch, one dental team, and one real clinical workflow.",
      footer: "AI-assisted clinical decision support. Final diagnosis and treatment decisions remain with the clinician."
    },
    auth: {
      back: "Back to Teta2", loginTitle: "Welcome back", loginCopy: "Sign in to your clinic workspace.", clinicSlug: "Clinic slug", identifier: "Email or username", password: "Password", signIn: "Sign in securely", signingIn: "Signing in…", noAccount: "New clinic?", registerLink: "Create clinic workspace", backendOnline: "Backend online", backendChecking: "Checking backend", backendOffline: "Backend unavailable",
      registerTitle: "Create your Teta2 clinic", registerCopy: "Complete the clinic profile now. Secure tenant provisioning will be connected to this exact flow in the backend stage.",
      clinicName: "Clinic name", city: "City", country: "Country", directorName: "Director name", workEmail: "Work email", phone: "Phone", slug: "Preferred clinic slug", branches: "Number of branches", plan: "Plan", passwordNew: "Create director password", submitRegistration: "Submit clinic application", applicationSaved: "Clinic application saved", applicationSavedCopy: "The frontend workflow is complete. In the backend stage this application will provision the tenant database, Director account, subscription, and billing state.", goLogin: "Go to sign in"
    },
    nav: { dashboard: "AI Workspace", patients: "My Patients", xrays: "X-rays", followups: "Follow-ups", radar: "Radar AI", outreach: "Outreach", settings: "Settings" },
    dashboard: {
      morning: "Good morning", subtitle: "Let's analyze and plan the best care for your patients.", recentPatients: "Recent Patients", viewAll: "View all", schedule: "Today's Schedule", analyses: "Recent Analyses", workspace: "AI Workspace", workspaceCopy: "Upload or capture an X-ray to get AI-powered insights", drop: "Drop & drop an X-ray image here", or: "or", upload: "Upload File", camera: "Take Photo", gallery: "From Gallery", supports: "Supports PNG, JPG, DICOM · Max size: 20MB", warning: "AI results are decision-support information, not diagnosis. Please review clinically.", radarTitle: "Radar AI pulse", radarCopy: "New treatment opportunities discovered across connected sources.", openRadar: "Open Radar AI", completed: "Completed", upcoming: "Upcoming", processing: "Processing", inReview: "In Review", noPatients: "No patients yet", noAnalyses: "Analyses will appear after the first OPG is processed.", noSchedule: "No follow-ups scheduled today." },
    common: { patient: "Patient", selectPatient: "Select patient", search: "Search", status: "Status", open: "Open", save: "Save", cancel: "Cancel", close: "Close", refresh: "Refresh", logout: "Log out", branch: "Branch", date: "Date", details: "Details", active: "Active", inactive: "Inactive", pending: "Pending", approved: "Approved", rejected: "Rejected", all: "All", loading: "Loading…", noData: "No data available", back: "Back", next: "Next", confirm: "Confirm", reject: "Reject" },
    workspace: { title: "AI Workspace", subtitle: "Review imaging, run Teta2 V5, and clinically validate findings.", uploadTitle: "New OPG", chooseXray: "Choose an X-ray", run: "Run Teta2 V5 Analysis", running: "Queueing analysis…", findings: "AI Findings", confidence: "Model score", tooth: "Tooth", finding: "Finding", review: "Clinical review", confirmed: "Confirmed", rejected: "Rejected", pendingReview: "Pending review", noAnalysis: "No analysis selected", noAnalysisCopy: "Upload an X-ray and run Teta2 V5 to start." },
    patients: { title: "My Patients", subtitle: "A longitudinal clinical record for every patient and every tooth.", id: "Patient ID", visits: "Visits", xrays: "X-rays", analyses: "Analyses", findings: "Findings", openWorkspace: "Open workspace" },
    xrays: { title: "X-ray Library", subtitle: "Private radiograph storage connected to the patient record.", filename: "Study", uploaded: "Uploaded", size: "Size", download: "Open image" },
    followups: { title: "Follow-ups", subtitle: "Upcoming monitoring, recall, and care continuity.", due: "Due", reason: "Reason", priority: "Priority", noData: "No follow-up records are currently loaded." },
    radar: { title: "Radar AI", subtitle: "Turn relevant social demand into an organized treatment-opportunity queue.", opportunities: "Opportunities", hot: "Hot", warm: "Warm", sources: "Active sources", signals: "Signals 24h", contact: "Review opportunity", platform: "Platform", treatment: "Treatment signal", score: "AI score", location: "Location", noData: "No Radar opportunities available yet." },
    outreach: { title: "Patient Outreach", subtitle: "Manage recall communication and clinic WhatsApp readiness.", connection: "WhatsApp connection", connected: "Connected", disconnected: "Disconnected", phone: "Patient WhatsApp", test: "Send test message" },
    settings: { title: "Settings", subtitle: "Clinic workspace, security context, and system diagnostics.", clinic: "Clinic ID", role: "Role", branches: "Branch scope", backend: "Backend health", language: "Language" },
    admin: {
      title: "Teta2 Platform Admin", subtitle: "Clinic operations, subscriptions, payments, and platform health.", loginTitle: "Platform administration", loginCopy: "Frontend preview of the protected platform-admin console. Backend admin authentication will replace preview access.", enterPreview: "Enter admin preview", overview: "Overview", clinics: "Clinics", payments: "Payments", subscriptions: "Subscriptions", activity: "Activity log", totalClinics: "Total clinics", activeSubscriptions: "Active subscriptions", pendingPayments: "Pending payments", mrr: "Monthly recurring revenue", clinic: "Clinic", owner: "Owner", location: "Location", plan: "Plan", subscription: "Subscription", payment: "Payment", renewal: "Next billing", actions: "Actions", approvePayment: "Approve payment", rejectPayment: "Reject payment", activateSubscription: "Activate subscription", suspendSubscription: "Suspend subscription", changePlan: "Change plan", monthlyPrice: "Monthly price", branches: "Branches", seats: "Seats", created: "Registered", paymentQueue: "Payment approval queue", paymentQueueCopy: "Confirm bank/manual payments before enabling the monthly subscription.", frontendMode: "Frontend control preview", frontendModeCopy: "Changes in this console are stored locally until the platform-admin backend API is implemented.", searchClinics: "Search clinics…", planStarter: "Starter", planGrowth: "Growth", planScale: "Scale", paid: "Paid", overdue: "Overdue", suspended: "Suspended", trial: "Trial", approve: "Approve", suspend: "Suspend", activate: "Activate", saveChanges: "Save changes", application: "New application" }
  },
  hy: {
    language: { title: "Ընտրեք լեզուն", subtitle: "Teta2-ի ամբողջ հարթակը կցուցադրվի ձեր ընտրած լեզվով։", english: "English", armenian: "Հայերեն", continue: "Շարունակել" },
    brand: { tagline: "Ատամների գնահատման և բուժման AI օգնական", platform: "AI ատամնաբուժական հարթակ" },
    public: {
      nav: { product: "Ապրանք", workflow: "Աշխատանքային հոսք", radar: "Radar AI", security: "Անվտանգություն", login: "Մուտք", register: "Սկսել կլինիկայի համար" },
      badge: "Կլինիկական AI՝ ժամանակակից ատամնաբուժական թիմերի համար",
      heroTitleA: "Տեսեք ավելին յուրաքանչյուր OPG-ում։", heroTitleB: "Հիշեք յուրաքանչյուր ատամը։ Վերադարձրեք պացիենտներին։",
      heroCopy: "Teta2-ը պանորամային ատամնաբուժական պատկերը դարձնում է խելացի երկարաժամկետ քարտ՝ օգնելով բժշկին վերանայել AI արդյունքները, պահպանել յուրաքանչյուր ատամի պատմությունը, պլանավորել հսկողությունը և Radar AI-ով գտնել բուժման նոր պահանջարկ։",
      heroPrimary: "Սկսել կլինիկայի գրանցումը", heroSecondary: "Բացել կլինիկայի վահանակը",
      proof1: "9 մասնագիտացված ONNX մոդել", proof2: "Մասնավոր X-ray պահոց", proof3: "Բժշկի պարտադիր հաստատում",
      sectionKicker: "Մեկ գործառնական շերտ՝ խելացի ստոմատոլոգիայի համար", sectionTitle: "Կլինիկական ինտելեկտ, պացիենտի շարունակականություն և աճ՝ մեկ հարթակում։",
      feature1Title: "OPG կլինիկական ինտելեկտ", feature1Copy: "Վերանայեք AI հայտնաբերումները ըստ ատամի, պահպանեք ապացույցը պացիենտի քարտում և յուրաքանչյուր արդյունք հաստատեք կլինիկորեն։",
      feature2Title: "Խելացի Recall", feature2Copy: "Կլինիկական արդյունքները վերածեք շարունակական խնամքի ժամանակացույցի՝ follow-up տրամաբանությամբ և կառուցվածքային հաղորդակցությամբ։",
      feature3Title: "Radar AI", feature3Copy: "Գտեք սոցիալական պահանջարկի համապատասխան ազդակները, դասակարգեք հնարավորությունները և թիմին տվեք հստակ կապի հերթ։",
      workflowKicker: "Պատկերից մինչև շարունակական խնամք", workflowTitle: "Աշխատանքային հոսք՝ կառուցված բժշկի շուրջ, ոչ թե մոդելի։",
      securityKicker: "Կառուցված կլինիկական վստահության համար", securityTitle: "Մասնավոր՝ նախագծմամբ։ Մարդու վերահսկմամբ՝ լռելյայն։",
      ctaTitle: "Տվեք ձեր կլինիկային խելացի երկրորդ շերտ։", ctaCopy: "Սկսեք մեկ մասնաճյուղից, մեկ թիմից և մեկ իրական կլինիկական հոսքից։",
      footer: "AI-ը կլինիկական որոշման աջակցման գործիք է։ Վերջնական ախտորոշումն ու բուժման որոշումը կատարում է բժիշկը։"
    },
    auth: {
      back: "Վերադառնալ Teta2", loginTitle: "Բարի վերադարձ", loginCopy: "Մուտք գործեք ձեր կլինիկայի աշխատանքային միջավայր։", clinicSlug: "Կլինիկայի slug", identifier: "Էլ․ փոստ կամ օգտանուն", password: "Գաղտնաբառ", signIn: "Անվտանգ մուտք", signingIn: "Մուտք…", noAccount: "Նոր կլինիկա՞", registerLink: "Ստեղծել կլինիկայի միջավայր", backendOnline: "Backend-ը հասանելի է", backendChecking: "Backend-ի ստուգում", backendOffline: "Backend-ը հասանելի չէ",
      registerTitle: "Ստեղծեք ձեր Teta2 կլինիկան", registerCopy: "Լրացրեք կլինիկայի տվյալները հիմա։ Անվտանգ tenant provisioning-ը backend փուլում կկապվի հենց այս հոսքին։",
      clinicName: "Կլինիկայի անվանում", city: "Քաղաք", country: "Երկիր", directorName: "Տնօրենի անուն", workEmail: "Աշխատանքային էլ․ փոստ", phone: "Հեռախոս", slug: "Ցանկալի clinic slug", branches: "Մասնաճյուղերի քանակ", plan: "Փաթեթ", passwordNew: "Ստեղծել տնօրենի գաղտնաբառ", submitRegistration: "Ուղարկել կլինիկայի հայտը", applicationSaved: "Կլինիկայի հայտը պահպանված է", applicationSavedCopy: "Frontend հոսքը պատրաստ է։ Backend փուլում այս հայտը կստեղծի tenant database-ը, Director հաշիվը, subscription-ը և billing վիճակը։", goLogin: "Անցնել մուտքին"
    },
    nav: { dashboard: "AI Workspace", patients: "Իմ պացիենտները", xrays: "Ռենտգեններ", followups: "Հետագա այցեր", radar: "Radar AI", outreach: "Հաղորդակցություն", settings: "Կարգավորումներ" },
    dashboard: {
      morning: "Բարի լույս", subtitle: "Եկեք վերլուծենք և պլանավորենք լավագույն խնամքը ձեր պացիենտների համար։", recentPatients: "Վերջին պացիենտները", viewAll: "Դիտել բոլորը", schedule: "Այսօրվա պլանը", analyses: "Վերջին վերլուծությունները", workspace: "AI Workspace", workspaceCopy: "Վերբեռնեք կամ նկարեք ռենտգեն՝ AI վերլուծության համար", drop: "Քաշեք և թողեք ռենտգեն պատկերը այստեղ", or: "կամ", upload: "Վերբեռնել ֆայլ", camera: "Լուսանկարել", gallery: "Պատկերասրահից", supports: "PNG, JPG, DICOM · առավելագույնը 20MB", warning: "AI արդյունքները որոշման աջակցման տեղեկատվություն են, ոչ ախտորոշում։ Խնդրում ենք կլինիկորեն ստուգել։", radarTitle: "Radar AI ազդակներ", radarCopy: "Միացված աղբյուրներից հայտնաբերված բուժման նոր հնարավորություններ։", openRadar: "Բացել Radar AI", completed: "Ավարտված", upcoming: "Սպասվող", processing: "Մշակվում է", inReview: "Ստուգման մեջ", noPatients: "Պացիենտներ դեռ չկան", noAnalyses: "Վերլուծությունները կհայտնվեն առաջին OPG-ի մշակումից հետո։", noSchedule: "Այսօր follow-up նախատեսված չէ։" },
    common: { patient: "Պացիենտ", selectPatient: "Ընտրել պացիենտ", search: "Որոնել", status: "Կարգավիճակ", open: "Բացել", save: "Պահպանել", cancel: "Չեղարկել", close: "Փակել", refresh: "Թարմացնել", logout: "Դուրս գալ", branch: "Մասնաճյուղ", date: "Ամսաթիվ", details: "Մանրամասներ", active: "Ակտիվ", inactive: "Ոչ ակտիվ", pending: "Սպասման մեջ", approved: "Հաստատված", rejected: "Մերժված", all: "Բոլորը", loading: "Բեռնվում է…", noData: "Տվյալ չկա", back: "Հետ", next: "Հաջորդ", confirm: "Հաստատել", reject: "Մերժել" },
    workspace: { title: "AI Workspace", subtitle: "Վերանայեք պատկերները, գործարկեք Teta2 V5-ը և կլինիկորեն հաստատեք արդյունքները։", uploadTitle: "Նոր OPG", chooseXray: "Ընտրել ռենտգեն", run: "Գործարկել Teta2 V5 վերլուծությունը", running: "Վերլուծությունը հերթագրվում է…", findings: "AI արդյունքներ", confidence: "Մոդելի միավոր", tooth: "Ատամ", finding: "Հայտնաբերում", review: "Կլինիկական ստուգում", confirmed: "Հաստատված", rejected: "Մերժված", pendingReview: "Սպասում է ստուգման", noAnalysis: "Վերլուծություն ընտրված չէ", noAnalysisCopy: "Վերբեռնեք ռենտգեն և գործարկեք Teta2 V5-ը։" },
    patients: { title: "Իմ պացիենտները", subtitle: "Երկարաժամկետ կլինիկական քարտ՝ յուրաքանչյուր պացիենտի և յուրաքանչյուր ատամի համար։", id: "Պացիենտի ID", visits: "Այցեր", xrays: "Ռենտգեններ", analyses: "Վերլուծություններ", findings: "Արդյունքներ", openWorkspace: "Բացել workspace-ը" },
    xrays: { title: "Ռենտգենների գրադարան", subtitle: "Մասնավոր ռադիոգրաֆիկ պահոց՝ կապված պացիենտի քարտին։", filename: "Պատկեր", uploaded: "Վերբեռնված", size: "Չափ", download: "Բացել պատկերը" },
    followups: { title: "Հետագա այցեր", subtitle: "Հսկողություն, recall և խնամքի շարունակականություն։", due: "Ժամկետ", reason: "Պատճառ", priority: "Առաջնահերթություն", noData: "Follow-up գրառումներ դեռ չկան։" },
    radar: { title: "Radar AI", subtitle: "Սոցիալական համապատասխան պահանջարկը վերածեք բուժման հնարավորությունների կազմակերպված հերթի։", opportunities: "Հնարավորություններ", hot: "Թեժ", warm: "Տաք", sources: "Ակտիվ աղբյուրներ", signals: "Ազդակներ 24ժ", contact: "Դիտել հնարավորությունը", platform: "Հարթակ", treatment: "Բուժման ազդակ", score: "AI միավոր", location: "Տեղադրություն", noData: "Radar հնարավորություններ դեռ չկան։" },
    outreach: { title: "Պացիենտների հաղորդակցություն", subtitle: "Կառավարեք recall հաղորդագրությունները և կլինիկայի WhatsApp պատրաստվածությունը։", connection: "WhatsApp կապ", connected: "Միացված", disconnected: "Անջատված", phone: "Պացիենտի WhatsApp", test: "Ուղարկել փորձնական հաղորդագրություն" },
    settings: { title: "Կարգավորումներ", subtitle: "Կլինիկայի միջավայր, անվտանգություն և համակարգի ախտորոշում։", clinic: "Կլինիկայի ID", role: "Դեր", branches: "Մասնաճյուղերի հասանելիություն", backend: "Backend վիճակ", language: "Լեզու" },
    admin: {
      title: "Teta2 Platform Admin", subtitle: "Կլինիկաներ, subscription-ներ, վճարումներ և հարթակի վիճակ։", loginTitle: "Հարթակի կառավարում", loginCopy: "Պաշտպանված platform-admin console-ի frontend նախադիտում։ Backend admin authentication-ը հետագայում կփոխարինի preview access-ը։", enterPreview: "Մուտք admin preview", overview: "Ամփոփում", clinics: "Կլինիկաներ", payments: "Վճարումներ", subscriptions: "Բաժանորդագրություններ", activity: "Գործողությունների մատյան", totalClinics: "Բոլոր կլինիկաները", activeSubscriptions: "Ակտիվ subscription-ներ", pendingPayments: "Սպասող վճարումներ", mrr: "Ամսական կրկնվող եկամուտ", clinic: "Կլինիկա", owner: "Սեփականատեր", location: "Տեղադրություն", plan: "Փաթեթ", subscription: "Subscription", payment: "Վճարում", renewal: "Հաջորդ վճարում", actions: "Գործողություններ", approvePayment: "Հաստատել վճարումը", rejectPayment: "Մերժել վճարումը", activateSubscription: "Ակտիվացնել subscription-ը", suspendSubscription: "Կասեցնել subscription-ը", changePlan: "Փոխել փաթեթը", monthlyPrice: "Ամսական գին", branches: "Մասնաճյուղեր", seats: "Օգտատերեր", created: "Գրանցված", paymentQueue: "Վճարումների հաստատման հերթ", paymentQueueCopy: "Հաստատեք բանկային/ձեռքով վճարումները մինչև ամսական subscription-ի ակտիվացումը։", frontendMode: "Frontend control preview", frontendModeCopy: "Այս console-ի փոփոխությունները պահվում են տեղական մինչև platform-admin backend API-ի ստեղծումը։", searchClinics: "Որոնել կլինիկաներ…", planStarter: "Starter", planGrowth: "Growth", planScale: "Scale", paid: "Վճարված", overdue: "Ժամկետանց", suspended: "Կասեցված", trial: "Փորձաշրջան", approve: "Հաստատել", suspend: "Կասեցնել", activate: "Ակտիվացնել", saveChanges: "Պահպանել", application: "Նոր հայտ" }
  }
} as const;

export type TetaCopy = typeof copy.en;
export function tr(lang: Lang): TetaCopy { return copy[lang] as TetaCopy; }
