-- DENTAI Product Intelligence V1, PostgreSQL/Supabase-compatible.
-- Application sets app.current_clinic_id for tenant-scoped requests.
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE clinics (clinic_id text PRIMARY KEY, name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE clinic_users (user_id text PRIMARY KEY, clinic_id text NOT NULL REFERENCES clinics, role text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE patients (patient_id text PRIMARY KEY, clinic_id text NOT NULL REFERENCES clinics, clinic_patient_number text, first_name text, last_name text, full_name text, date_of_birth date, sex text, phone text, email text, external_patient_id text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(clinic_id,clinic_patient_number));
CREATE TABLE patient_identifiers (identifier_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), clinic_id text NOT NULL REFERENCES clinics, patient_id text NOT NULL REFERENCES patients, identifier_type text NOT NULL, identifier_hash text NOT NULL, encrypted_value text, verified boolean NOT NULL DEFAULT false, UNIQUE(clinic_id,identifier_type,identifier_hash));
CREATE TABLE opg_studies (study_id text PRIMARY KEY, clinic_id text NOT NULL REFERENCES clinics, patient_id text REFERENCES patients, study_date date, source_type text NOT NULL, study_instance_uid text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE opg_images (image_id text PRIMARY KEY, clinic_id text NOT NULL REFERENCES clinics, study_id text NOT NULL REFERENCES opg_studies, storage_provider text NOT NULL, storage_bucket text NOT NULL, storage_key text NOT NULL, sha256 text NOT NULL, mime_type text NOT NULL, size_bytes bigint NOT NULL, asset_role text NOT NULL DEFAULT 'CLINICAL_ORIGINAL', created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(storage_provider,storage_bucket,storage_key));
CREATE TABLE identity_extractions (extraction_id text PRIMARY KEY, clinic_id text NOT NULL REFERENCES clinics, study_id text NOT NULL REFERENCES opg_studies, source text NOT NULL, encrypted_payload text, status text NOT NULL, confidence numeric, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE identity_confirmations (confirmation_id text PRIMARY KEY, clinic_id text NOT NULL REFERENCES clinics, study_id text NOT NULL REFERENCES opg_studies, patient_id text REFERENCES patients, user_id text NOT NULL REFERENCES clinic_users, action text NOT NULL, conflict_reasons jsonb NOT NULL DEFAULT '[]', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE model_versions (model_version text PRIMARY KEY, manifest_sha256 text NOT NULL, manifest jsonb NOT NULL, frozen_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE dental_analyses (analysis_id text PRIMARY KEY, clinic_id text NOT NULL REFERENCES clinics, study_id text NOT NULL REFERENCES opg_studies, model_version text NOT NULL REFERENCES model_versions, thresholds jsonb NOT NULL, ai_output jsonb NOT NULL, analysis_timestamp timestamptz NOT NULL DEFAULT now());
CREATE TABLE tooth_predictions (tooth_prediction_id text PRIMARY KEY, clinic_id text NOT NULL REFERENCES clinics, analysis_id text NOT NULL REFERENCES dental_analyses, fdi text NOT NULL, bbox jsonb NOT NULL, confidence numeric NOT NULL, status text, review_required boolean NOT NULL, raw_evidence jsonb NOT NULL, UNIQUE(analysis_id,fdi));
CREATE TABLE finding_predictions (finding_prediction_id text PRIMARY KEY, clinic_id text NOT NULL REFERENCES clinics, tooth_prediction_id text REFERENCES tooth_predictions, analysis_id text NOT NULL REFERENCES dental_analyses, finding_type text NOT NULL, confidence numeric, source text NOT NULL, bbox jsonb, experimental boolean NOT NULL DEFAULT false);
CREATE TABLE doctor_reviews (review_id text PRIMARY KEY, clinic_id text NOT NULL REFERENCES clinics, analysis_id text NOT NULL REFERENCES dental_analyses, tooth_prediction_id text REFERENCES tooth_predictions, doctor_id text NOT NULL REFERENCES clinic_users, doctor_action text NOT NULL, original_ai_output jsonb NOT NULL, corrected_value jsonb, notes text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE verified_labels (verified_label_id text PRIMARY KEY, clinic_id text NOT NULL REFERENCES clinics, analysis_id text NOT NULL REFERENCES dental_analyses, tooth_prediction_id text REFERENCES tooth_predictions, state text NOT NULL, label_payload jsonb NOT NULL, verified_by text REFERENCES clinic_users, verified_at timestamptz, policy_reference text);
CREATE TABLE followup_plans (followup_id text PRIMARY KEY, clinic_id text NOT NULL REFERENCES clinics, patient_id text NOT NULL REFERENCES patients, study_id text NOT NULL REFERENCES opg_studies, tooth_fdi text, risk_level text NOT NULL, min_months integer NOT NULL, max_months integer NOT NULL, target_date date NOT NULL, reasons jsonb NOT NULL, doctor_overridden boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE reminders (reminder_id text PRIMARY KEY, clinic_id text NOT NULL REFERENCES clinics, patient_id text NOT NULL REFERENCES patients, case_id text NOT NULL, tooth_fdi text, reminder_type text NOT NULL, scheduled_at timestamptz NOT NULL, channel text NOT NULL, status text NOT NULL, message_template text NOT NULL, created_by text NOT NULL REFERENCES clinic_users, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE longitudinal_changes (change_id text PRIMARY KEY, clinic_id text NOT NULL REFERENCES clinics, patient_id text NOT NULL REFERENCES patients, previous_analysis_id text REFERENCES dental_analyses, current_analysis_id text NOT NULL REFERENCES dental_analyses, tooth_fdi text, change_state text NOT NULL, change_payload jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE learning_records (learning_record_id text PRIMARY KEY, clinic_id text NOT NULL REFERENCES clinics, source_case_id text NOT NULL, source_model_version text NOT NULL REFERENCES model_versions, verification_status text NOT NULL, deidentification_status text NOT NULL, training_eligibility boolean NOT NULL DEFAULT false, consent_or_policy_reference text, deidentified_image_id text REFERENCES opg_images, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE audit_log (audit_id bigserial PRIMARY KEY, clinic_id text NOT NULL REFERENCES clinics, user_id text, patient_id text, case_id text, action text NOT NULL, entity_type text NOT NULL, entity_id text NOT NULL, timestamp timestamptz NOT NULL DEFAULT now(), before_reference text, after_reference text, ip_address inet, request_id text);

-- Tenant isolation. Service roles may bypass RLS only through explicit DB privileges.
DO $$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['clinic_users','patients','patient_identifiers','opg_studies','opg_images','identity_extractions','identity_confirmations','dental_analyses','tooth_predictions','finding_predictions','doctor_reviews','verified_labels','followup_plans','reminders','longitudinal_changes','learning_records','audit_log'] LOOP
  EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',t);
  EXECUTE format('CREATE POLICY %I_clinic_isolation ON %I USING (clinic_id = current_setting(''app.current_clinic_id'', true)) WITH CHECK (clinic_id = current_setting(''app.current_clinic_id'', true))',t,t);
 END LOOP;
END $$;
-- audit_log is append-only at the application role level: grant INSERT/SELECT, never UPDATE/DELETE.
